### ISSUE TITLE
.secrets.toml not read automatically

### ISSUE THREAD

**Issue by thmsklngr** [dynaconf/dynaconf#1004]
Hi there,

currently I'm evaluating various libraries for settings management in my next project. One favorite is Dynaconf, it relly shines! :)
One thing which makes me wonder is that according to the docs the file `.secrets.toml` should be automatically read, shouldn't it?
Example:
```
# conf/myprog.toml
BASE='/some/path'
SECRET_KEY='abc123'

# conf/myprog.local.toml
BASE='/foo/bar'

# conf/.secrets.toml
SECRET_KEY='wildwilly'
```
Running a normal Python shell I import the settings and showed the result:
```
>>> from dynaconf import Dynaconf
>>> settings = Dynaconf(root_path='conf', merge_enabled=true, settings_files=['myprog.toml'])
>>> settings.to_dict()
{'BASE': '/foo/bar', 'SECRET_KEY': 'abc123'}
```
To my understanding `SECRET_KEY` should be `wildwilly`. So why it is not changed in the result? Or do I have to specify .secrets.toml explicitly in settings_files? Btw, it does not matter, if .secrets.toml is under conf or in the directory above (from where I started the interpreter from).

Dynaconf version is 3.1.5.

Many thanks

**Comment by pedro-psb** [comment]
Hello @thmsklngr, glad you are enjoying Dynaconf!

I believe that it actually have to be loaded explicitly.

I had a look in the docs (Secrets and Configuraiton, mostly) and didn't find any specific line that states that it should be loaded automatically. Also, I've found some "counter-examples" that show explicitly loading of it: [on config page](https://www.dynaconf.com/configuration/#on-instance-options) and on [functional tests](https://github.com/dynaconf/dynaconf/blob/c5d9f2f36f07aabf002eaa199891a39317a07507/tests_functional/django_example/foo/settings.py).

Is there a particular place that suggest this behavior?

**Comment by thmsklngr** [comment]
Well, taking a look into "Merging" it would imply to me that it is automatically loaded.

https://www.dynaconf.com/merging/#local-configuration-files-and-merging-to-existing-data

**Comment by pedro-psb** [comment]
Oh, I see.
I agree there is room for ambiguity, as the example does not show how `Dynaconf` object is instantiated.

We should add something like that to clarify that `.secrets.toml` was not loaded automatically.

```diff
So with the above eg, the values will be:

+ settings = Dynaconf(settings_files=["settings.toml", ".secrets.toml"])
settings.COLORS == ["pink"]
settings.PARAMETERS == {"enabled": False}
settings.PASSWORD == 9999
```

**Comment by limeiralucas** [comment]
I'm taking this one 😃
