### ISSUE TITLE
Can settings.local.toml stay in parent folder of settings.toml?

### ISSUE THREAD

**Issue by hongquan** [dynaconf/dynaconf#1018]
For now, after finding `settings.toml`, Dynaconf will look for `settings.local.toml` in the same folder. Dynaconf doesn't look up further in parent folder. Could this be changed?

**Comment by pedro-psb** [comment]
Hello @hongquan 
There is no official way to do that. We have a plan to implement a more flexible file-finding mechanism #923, but that is not a core priority right now.

For the records, it shouldn't be hard to implement a really basic overriding mechanism for the finding functions, which are mostly [here](https://github.com/dynaconf/dynaconf/blob/master/dynaconf/utils/files.py).

**Comment by hongquan** [comment]
Thank you.
