### ISSUE TITLE
[RFC] add `@get` converter

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#1038]
I need to add a new converter called `@get` to be used to simply call `settings.get` with specified key and use whatever value is there with the current type.

Example:

```python
from dynaconf import Dynaconf
settings = Dynaconf(settings_files=["a.py", "b.py"])

# a.py
THING = "value"

# b.py
ANOTHER_THING = "@get THING"
```

This is different than using `this` inside a lazy `@format/@jinja` because those 2 would cast to string by default or to specified combo like `@int @format {this[THING]}`.

The `@get` would just attempt to perform a `settings.get` and use whatever value is there, it will also allow a default to be specified.

```python
THING = "@get THING @int 789"
```

The above will translate to 

```python
settings.get("THING", default="789", cast="@int")
```

Not sure if this must be lazily evaluated.

This feature will allow the fix of https://github.com/pulp/pulp_ansible/pull/1130 

## Implementation

On https://github.com/dynaconf/dynaconf/blob/6322c4dc4afe0c91160cbdfb069119ca815a60a1/dynaconf/utils/parse_conf.py#L242-L278 

```python
"@get": lambda value: Lazy(value, formatter=getter_formatter)
```

then implement the `getter_formatter` as a function that takes `value` as `"THING @int 789"` parses it and resolves to `settings.get()` call.

**Comment by rochacbruno** [comment]
https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html can be used to solve the tokenization

**Comment by pedro-psb** [comment]
Would `pyparsing` be vendored?

**Comment by rochacbruno** [comment]
@pedro-psb I am not sure yet if we really need pyparsing or if we can solve it by using a simple split() and maybe regexp.

If we need pyparsing, then we must avoid vendoring it and make this feature optional, as an extra dependency to install, not added by default.

```python
THING = "@get VAR @int"
# ImportError, pyparsing is not installed
# pip install pyparsing
```

but probably we can solve with simple split and regex as we have few tokens to extract.

```
@get {variable_name}
@get {variable_name} {@cast}
@get {variable_name} {@cast} {default value}
@get {variable_name} {default value}
```

there are 4 valid states and we can match them using a regexp over the structure. (as long as the default value doesnt start with @
