### ISSUE TITLE
Improve documentation on cast and default

### ISSUE THREAD

**Issue by q-wertz** [dynaconf/dynaconf#1039]
Currently it is not clear from the documentation when using `default` together with `cast`, whether 

1. the default value has to be given as string/int/etc. and the cast is done on it
2. the default value has to be given in the correct type
3. It doesn't matter

e.g.
```
import enum

import dynaconf as dc

class VisCheck(enum.StrEnum):
    NONE = enum.auto()
    A = enum.auto()
    B = enum.auto()


# Variant 1
dc.Validator(
    "VISIBILITY_CHECK",
    default="a",
    cast=VisCheck,
)

# Variant 2
dc.Validator(
    "VISIBILITY_CHECK",
    default=VisCheck.A,
    cast=VisCheck,
)
```

It would be nice to have a hint in the docs :)

EDIT: Wrong default type in Variant 2 (typo)

**Comment by pedro-psb** [comment]
Hey @q-wertz , option 1 is correct, cast is called for defaults.
Agreed that this can be more clear in the docs!

**Comment by q-wertz** [comment]
Not sure if I oversee something, but it looks like both solutions work in my case.
When I do not have the value in my config file, the default `VisibilityCheck.A` is in the settings. When I set it to an onject with invalid type (e.g. `np.random.default_rng()`) it fails with 

`Generator(PCG64) at 0x7F64087CF840 is not a valid VisibilityCheck`

For me from "user" view it looks like both variants are equivalent :sweat_smile:

**Comment by pedro-psb** [comment]
Yeah, I guess they are equivalent because the casting function will usually bypass the value when called over an already casted value (like `VisCheck(VisCheck('a'))`).
We can say that it's usually equivalent, but I suggest describing that the cast is called for defaults.

**Comment by rochacbruno** [comment]
cast and default will be revmoved from validators to use the typed dynaconf schema
