### ISSUE TITLE
[RFC] Pydantic Schema Validation

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#1045]
This RFE has potential to replace the proposal I made on #683 

Which is the support for the following snippet

```python
from pydantic import BaseModel, ConfigDict
from dynaconf import Dynaconf, DynaBox


class MySchema(BaseModel):
    model_config = ConfigDict(extra='allow')
	dynaconf_config = DynaBox(lazy_validation=True, settings_files=["settings.yaml"])

    server: str
    port: int


settings = Dynaconf(
    schema=MySchema,  # replaces `validators` and is mutually exclusive
)

settings.set("server", 1234)  
# don't raise because lazy_validation=True
# if lazy_validation was false then .set would assume the need for validation

print(settings.server)  
# raise validation error because settings is evaluated on the first attr access
```

Details:

- Must keep the current `validators` working with no regression, the only caveat is that the user must choose only one validation strategy to use to avoid confusions
- On Django the schema must be defined(or imported) inside the app/settings.py and passed to DjangoDynaconf, the same for FlaskDynaconf.
- If validation is not lazy, then it will be called for every .set or .update, we have to ensure that inside loaders we can load multiple keys in bulk and validate once
- Pydantic is not added as a hard dependency, can be added on the extra section, but on the docs it must be described to install pydantic along with Dynaconf
- Support for Pydantic v2 only
- Before invoking the validation, the keys on `settings.as_dict()` must be transformed to the proper case, the way it is defined on the schema (not sure if pydantic allows case insensitivity)

**Comment by pedro-psb** [comment]
There is a downside I overlooked about using composition over inheritance that I've overlooked in our last discussion: we don't get auto-complete out of the box (with composition), which is a very requested feature related to schema-based config.

**Comment by rochacbruno** [comment]
@pedro-psb we can fix that with composition, python is very permissive.

![2024-01-30_16-28_1](https://github.com/dynaconf/dynaconf/assets/458654/fafa14e1-8dce-4d8a-a248-103d094b93ff)
![2024-01-30_16-28](https://github.com/dynaconf/dynaconf/assets/458654/c8a69930-a519-4c75-9e3b-7263647a1d26)
![2024-01-30_16-26](https://github.com/dynaconf/dynaconf/assets/458654/e18e58b8-2716-442a-a723-6d4c7bd68e52)

**Comment by rochacbruno** [comment]
replaced by #1107
