### ISSUE TITLE
Broken link to source code in docs

### ISSUE THREAD

**Issue by mitches-got-glitches** [dynaconf/dynaconf#1059]
Following this link leads to a 404 error. Perhaps it should link to the source on GitHub directly, or be included on the page with `mkdocstrings`? [Click on PrefixFilter here](https://www.dynaconf.com/configuration/?h=filter#filtering_strategy) to test.
https://github.com/dynaconf/dynaconf/blob/0390393c27a7ef27104bbda2426b3382dcc7fb9f/docs/configuration.md?plain=1#L240

**Comment by pedro-psb** [comment]
Its looks like an end user-facing API, so we could include that in mkdocstrings. I think there is a special syntax to link mkdocstrings-generated API that don't require using the publish link, it would be nice to use that.

IMO, one good way to organize this would be:

Reference/
--API/
----`dynaconf`
----`dynaconf.strategies`

Note the code style in the title. You can customize the title display by using a h1 header in the markdown documents (e.g, ``# `dynaconf` ``)
