### ISSUE TITLE
[bug] Validation on Dynaconf instantiation not working

### ISSUE THREAD

**Issue by mitches-got-glitches** [dynaconf/dynaconf#1068]
**Describe the bug**
The [docs state that validation should occur on instantiation](https://www.dynaconf.com/validation/#on-instantiation) when passing the `validators` argument to `Dynaconf` but no errors seem to be raised for the given example. I've produced my own example too and I get the same issue.

**To Reproduce**

2. Having the following config files:

<details>
<summary> Config files </summary>

**settings.toml**

Taken from https://www.dynaconf.com/validation/#overview

```toml
[default]
version = "1.0.0"
age = 35
name = "Bruno"
DEV_SERVERS = ['127.0.0.1', 'localhost', 'development.com']
PORT = 8001
JAVA_BIN = "/usr/bin/java"

[production]
PROJECT = "This is not hello_world"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**config.py**

Validators set up as: https://www.dynaconf.com/validation/#on-instantiation

```python
from dynaconf import Dynaconf, Validator

settings = Dynaconf(
    settings_files=["settings.toml"],
    environments=True,
    validators=[
        # Ensure some parameter meets a condition
        Validator('AGE', lte=30, gte=10),
        # validate a value is eq in specific env
        Validator('PROJECT', eq='hello_world', env='production'),
    ]
)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python config.py
```

</details>

**Expected behavior**
Expected validation errors to be raised on instantiation of `Dynaconf` but everything runs until the end.
Documented behaviour says that two errors should be raised: https://www.dynaconf.com/validation/#on-instantiation

Validation doesn't seem to be triggered until a setting is accessed. Maybe this is intended because of the Lazy behaviour, but the docs should say so in this case.

The following three lines will trigger a validation error. 

```python
print(settings.age)
print(settings.validators)
print(settings.as_dict())
```

However, only a single Validation error is returned whereas the docs say that two Validation errors will be returned. I think this is expected Python behaviour and may need to be presented clearer in the docs.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Dynaconf Version: 3.2.4
 - Python 3.11.4

**Additional context**

**Comment by pedro-psb** [comment]
This is a documentation error.
* The intended behavior is to have it trigger upon access.
* Only the first error is raised on the instantiation validation
