### ISSUE TITLE
Validation doc section "On instantiation" improvement

### ISSUE THREAD

**Issue by mitches-got-glitches** [dynaconf/dynaconf#1069]
I think the example given in the docs here could do with some improvement to make it clearer:

https://github.com/dynaconf/dynaconf/blob/4ab518393a1f7aa72e353a485aebea2852561120/docs/validation.md?plain=1#L36-L58

1. It refers to the example `settings.toml` given in [this section](https://www.dynaconf.com/validation/#overview), so I feel like the example should have `settings_files=["settings.toml"]` and `environments=True` so that a user can easily recreate a working example.
2. `Path` is imported here but not used
3. The horizontal whitespace between validators could be taken out
4. The will raise section at the end could be presented better, and currently it doesn't seem to be accurate because of a potential bug #1068

**Comment by pedro-psb** [comment]
> 3. The horizontal whitespace between validators could be taken out

Do you mean the vertical in L49? I think it helps keeping the comment well grouped with its subject.

Otherwise, I agree.

**Comment by pedro-psb** [comment]
Closed by #1076
