### ISSUE TITLE
[CI] New release process

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#1072]
This replaces the non-changelog part of #1026.

## Problem
Informing the release version at the moment of the release is error-prone.

## Solution
Conceptually: keep the version in the files (`dynaconf/VERSION` and `mkdocs.yml`) represent the actual developer version (`x.y.z.dev`), which is the next version to be released (`x.y.z`).

In practice:
- have a script that creates two release-related commits, as proposed below.
- create a development section in the docs and include the releasing process.

## Alternatives
None.

## Additional context

Illustration of the desired process:

![proposal new dynaconf release process - Frame 1](https://github.com/dynaconf/dynaconf/assets/7907864/74bc0b51-102f-4b99-8ed9-b26c401e8d14)

**Comment by mitches-got-glitches** [comment]
It might be worth considering this project [bump-my-version](https://github.com/callowayproject/bump-my-version) to implement your solution to this process. You can serialize the versioning however you want, adding additional parts such as `.dev` and `.next.dev`, and ensure things follow the order you prescribe.

It can tag and commit for you too.

**Comment by pedro-psb** [comment]
Yeah, I was intending to use that! I've looked into bump2version, but they are now pointing to this one.
