### ISSUE TITLE
[RFC] Add `as_dict` alias to `to_dict` for `DynaBox` for consistency between `LazySettings` and `DynaBox` objs 

### ISSUE THREAD

**Issue by mitches-got-glitches** [dynaconf/dynaconf#1073]
**Is your feature request related to a problem? Please describe.**
It's possible to convert a `LazySettings` object to a Python dictionary with `LazySettings.as_dict()`, and there is an alias to `to_dict` for backwards compatibility. The `DynaBox` class inherits from the `Box` class which comes from a vendor. There is the method `Box.to_dict()` 
but not `.as_dict()`, so there is an inconsistency for the user if the user accesses a sub-box of settings and then tries to convert to a dictionary - see context.

**Describe the solution you'd like**
Add an alias to `DynaBox`:

```python
class DynaBox(Box):
    ...
    as_dict = to_dict
```

The opposite of what is done here:
https://github.com/dynaconf/dynaconf/blob/4ab518393a1f7aa72e353a485aebea2852561120/dynaconf/base.py#L424

**Describe alternatives you've considered**
| No | Alternative                                                                           | Drawback                                                                            |
|----|---------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| 1  | Using a combination of `as_dict()` and `to_dict()`                                    | confusing for the user                                                              |
| 2  | Using `to_dict()` for both `LazySettings` and `DynaBox`                               | seems like this is the older method and the current guidance is to use `as_dict()`  |
| 3  | Doing only `LazySettings.as_dict()` and then using keys to get to dict level we want  | takes away the flexibility of using dot notation to get to sub-levels of config     |

**Additional context**

#### nested_settings.toml
```toml 
[hyperparameters]
max_depth = 10
n_estimators = 20
```

#### Examples

```python
from dynaconf import Dynaconf
settings = Dynaconf(settings_files=['nested_settings.toml'])

print(settings.as_dict())
>>> {'HYPERPARAMETERS': {'max_depth': 10, 'n_estimators': 20}}

print(settings.hyperparameters.as_dict())
>>> dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'as_dict'"

print(settings.hyperparameters.to_dict())
>>> {'max_depth': 10, 'n_estimators': 20}
```

**Comment by pedro-psb** [comment]
This looks reasonable to me.
Cant see why not.

**Comment by rochacbruno** [comment]
DynaBox will go away (hopefuly) as part of #1128 #1129 this issue will be referenced on those issues so we take care this is considered on the new DictValue
