### ISSUE TITLE
[RFC] Provide workaround for auto-complete w/ Schema

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#1082]
## Problem

I want to be able to use a schema object to provide type hints for my `settings` object:

```python
class MySchema(DynaconfBase):
    name: str
    age: int

settings = Dynaconf()
settings.na # IDE autocomplete "name" and recognizes as string
```

## Proposal

Fake the type of the Dynaconf object by pretending it is a Schema object.

To provide both Schema attributes and Dynaconf's usual methods, we could provide a base Schema to be inherited, which will act as a stub, providing only docstrings and type hinting to Dynaconf object methods.

- **pro:**
  - we avoid the efforts of significantly changing how dynaconf works (backward-compatibility safety)
  - we avoid the complexity a big change would bring (we have limited maintainability power).
- **cons:**
  - Not very elegant (but it's not unpractical either, I would argue).

```python
from dynaconf import DynaconfBase, Dynaconf

class MySchema(DynaconfBase):
    name: str
    age: int
    
settings: MySchema = Dynaconf(...) # type: ignore
settings.set # shows annotations for dynaconf set method
settings.na # suggests name: str
```

It could work along with this more recent [Schema Validation proposal](https://github.com/dynaconf/dynaconf/issues/1045):

```python
# Not elegant, but practical and backward-compatible safe
settings: MySchema = Dynaconf(schema=MySchema) # type: ignore
```

## Alternatives

- [This draft PR](https://github.com/dynaconf/dynaconf/pull/677) should provide that, but it falls into the complexity issue
- Maybe there is another kind of trick we can do that won't require the `# type: ignore`, but I'm not sure what.

## Additional Context

I did some limited testing around that.
- Django setups might provide some trouble to do that.
- We could try on more IDEs (experimented with Helix and Vscode).

**Comment by breakid** [comment]
Recently, I've been working on adding type hints to a Flask config. I, independently, came up with essentially the same solution and would really like to see this functionality built into Dynaconf.

For reference, I got around the need for `#type: ignore` by casting it to my schema (after checking that all of the settings had the correct type, of course). In your example, it would look something like this:

```python
from typing import cast
from dynaconf import Dynaconf

class MySchema(Dynaconf):
    name: str
    age: int
    
settings: MySchema = cast(MySchema, Dynaconf(...))
```

If the schema was passed to Dynaconf as in the example: `settings: MySchema = Dynaconf(schema=MySchema)`, the cast could happen internal to Dynaconf, which would be cleaner from the end user perspective.

**Comment by pedro-psb** [comment]
That's nice, I didn't know about cast, thanks for sharing!
I did some small experiment by casting internally and it does seems to work.
I'll try to get some time to work on this.

**Comment by rochacbruno** [comment]
Remaining tasks from #1110

- [ ] Assign Schema to the Settings class so it can be accessed later during loading process
- [ ] Handle tuple type `field: tuple[T, T, T]` + Annotated and enclosed in list and dict variations
- [ ] Handle Any type in all cases
- [ ] Handle Totality and Allow Extra
- [ ] Implement `Annotated[int, ReadOnly] = 1`
- [ ] Implement `Annotated[int, ReadFrom("env", "yaml")]`
- [ ] Implement Alias
- [ ] Handle Description as annotation arg
- [ ] Support expressions?
- [ ] Generate sample config file from schema
- [ ] Generate schema from runtime settings
- [ ] Automatically cast settings to the typed setting? (on loader? on validation?)
- [ ] Merge default from schema with data loaded by loaders
- [ ] Improve validator messages (breaking change, post 4.0)
- [ ] Drop`default` from Validator (breaking change, post 4.0)
- [ ] Replace `cast` on Validator with `pre_validation`, this callable would apply only pre_validation and not mutate settings.
- [ ] Support Schema on FlaskDynaconf
- [ ] Support Schema on DjangoDynaconf

**Comment by rochacbruno** [comment]
I think we can close this one, I opened separate issues marked with typed label
