### ISSUE TITLE
k8s file-mounted secrets

### ISSUE THREAD

**Issue by zalmane** [dynaconf/dynaconf#1092]
In K8S, it is common to mount secrets to a file such as tmpfs.
The typical format puts each secret into a separate file inside a mounted volume, where the key is the filename and the content is the value.
Is there a way to achieve loading this in Dynaconf? 
If not, what is the best way to add this functionality (using hooks or plugin, or contribute a PR?).

**Comment by sebastian-correa** [comment]
I think this could be done with access hooks as well! See #1160.

You could define a custom format for these kinds of secrets, like setting their values in your YAML (or TOML, or wherever) to `__k8s_file_mounted:path_to_file` and then define an access hook similar to the one proposed in the example in #1160 that, when `isinstance(result, str) and result.startswith("__k8s_file_mounted")` does something like

```python
secret_file = Path(result.split(":")[-1]) / key
with secret_file.open("r") as file:
    CACHE[key] = file.readtext()
    return CACHE[key]
```

and you should be good to go. We do a very similar thing and it's worked out wonderfully for us to get secrets from GCP secret manager upon first access to the keys (and not when instantiating the `Dynaconf` instance, which can make it slow for no good reason).

**Comment by rochacbruno** [comment]
You are right @sebastian-correa I think right now 
the best approach is to use Access Hook.

On the new Secret type I want to add bultin support for mounted secrets as it is a common use case on cloud deployments.

So this issue might be covered on #1152
