### ISSUE TITLE
[RFC] Suport sub types

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#1108]
#1107 introduces tech preview of Typed Settings

Now the next feature to be added is SubTypes

right now every attribute on typed.Dynaconf must have a type annotation or a VAlidator, but it doesnt allow yet to have a custom type.

```
 class Database:       
    host: str       
    port: Annotated[int, Validator(gt=999)] 

 class Settings(Dynaconf):      
    database: Database
```

  For this to work, we might need to have the subschema to also contribute to Validators and its value casted, because on the raw settings there will be `{"database": {...}}` and not the instance of Database

**Comment by pedro-psb** [comment]
Closed by #1109
