### ISSUE TITLE
Instantiating Dynaconf can be slow

### ISSUE THREAD

**Issue by sebastian-correa** [dynaconf/dynaconf#1158]
#Summary
I'll preface with a _thank you_ for the work you've done in Dynaconf. We've been using it for a while now and it's helped our dev team considerably.
 
We're using Dynaconf to load ~14 YAML files. Due to our package's `__init__.py`, Dynaconf is one of the first things that loads and it's become a bit too slow for us, as startup takes ~2s-4s most of which is Dynaconf:

<img width="544" alt="image" src="https://github.com/dynaconf/dynaconf/assets/43179146/f799831e-4411-4e2a-bc59-f8b0fa863ace">

This is how we declare the `Dynaconf` object:

```python
settings = Dynaconf(
    settings_files=_list_of_14_yamls,
    environments=True,
    env_switcher="PROJECT_STAGE",
    envvar_prefix="PROJECT",
    merge_enabled=True,
    post_hooks=[cast_settings],
)
```
where the `cast_settings` function is a simple function that does things like `settings["some"]["setting"] = SomeEnum[settings["some"]["setting"]]`.

I've been profiling our code and found that the biggest culprits seem to be `Validator`s and `execute_module_hooks`. In our case, these account for ~0.8s-1.5s and ~0.7s of startup time. The casting function takes about ~0.4s as well, but that seems unavoidable in our case (not using casting from `Validator`s because it gave trouble some time ago; I haven't checked in recent versions).

## Validation
Of the validation time, 2 `Validator`s take most of the time (one that checks ~22 settings takes ~0.4s and another with ~11 takes ~0.2s):

```python
slow_validators = [
    Validator(*long_list, cast=float, default=0.0),
    Validator(*long_list_2, must_exist=True, cast=float),
]
```

Does this runtime for each of these validators make sense to you?

## `execute_module_hooks`
The call to `execute_module_hooks` in `Settings.__init__` seems to want to import 1 `dynaconf_hooks.py` file per YAML we tried to load. This results in calls to `py_loader.import_from_filename`, which takes some time.

For this, I propose to add

```python
    if not os.path.exists(filename):
        # Return early if file doesn't exist (can't be imported). Faster than attempting to import.
        return
```

at the very top of `import_from_filename`. I can contribute this with a PR if it's something you'd accept though I could also research this function further to find the actual culprit of the delay. In our case, this solution brought down runtime from ~0.7s to ~0.1ms.

**Comment by rochacbruno** [comment]
Hi, thanks for the detailed information,

I agree with adding the improvement you mentioned and we can do further investigation to improve Validator execution.

As you are using multiple names on a Validator it is going 
to be a exponential loop over names + operations.

Right now there's is a known issue of Validator where it calls .set twice, which is a issue we plan to solve for 4.0.0

**Comment by rochacbruno** [comment]
@sebastian-correa I applied your suggestion on https://github.com/dynaconf/dynaconf/pull/1159 
that actually had to go before the call to import_from_filename but the result might be the same

**Comment by rochacbruno** [comment]
I investigated the `Validator` problem, and it is for sure related to the known issue of mutating settings during validation, this fix requires a breaking change that will come on 4.0.0 which is the removal of `cast` and `default` from `Validator` in favor of using the new `typed.Dynaconf` schema to define defaults and types.

For now my recommendation is to stop using those 2 validators, as all they do is casting ad defaults and replace those with a hook_function


```py
def custom_validate_settings(settings) -> dict:
    # Settings in this context is immutable, you must return a dict
    data = {}
    keys_i_want_to_validate = ["x", "p", "t", "o"]
    required_keys = ["x", "o"]
    for key in keys_i_want_to_validate:
        value = settings.get("key")
        if value is None and key in required_keys:
            raise ValidationError(f"{key} is required")
        data[key] = float(value or 0.0)  # cast and default
    return data


settings = Dynaconf(
    settings_files=_list_of_14_yamls,
    environments=True,
    env_switcher="PROJECT_STAGE",
    envvar_prefix="PROJECT",
    merge_enabled=True,
    post_hooks=[cast_settings, custom_validate_settings],
)
```

We are planning for 4.0.0 and there is one issue #1143 to track the changed we are going to implement, on 4.0.0 you will be able to define default value and casting in the schema

```py
# on tech preview for 3.3.0, to be GA on 4.0.0

class Settings(Dynaconf):
    number: float = 0.0   # has default, casted to float
    other_number: float   # required, casted to float
    even_other: Annotated[float, Gt(1.1), IsIn(my_enum), Cast(custom_casting)]
```

**Comment by rochacbruno** [comment]
yes please put questions/suggestions there or #1150 

Right now fetching remote secrets are done by using Vault or Redis and the current implementation just loads all the keys from one of those buckets.

The future impl must be more clever and now that we will have a schema, that will be possible to mark specific variable as a secret

**Comment by sebastian-correa** [comment]
Will post there. CLosing this for now as the validator is already in the works for v4. Thank you!
