### ISSUE TITLE
dynaconf_include definition precedence 

### ISSUE THREAD

**Issue by AndreasAlbert** [dynaconf/dynaconf#245]
When using `dynaconf_include` inside a configuration file, the imported file seems to get precedence over the file the inclusion is done from.  Is there a way to reverse this behavior? 

Example:

`base_config.yml`:
```yaml
default:
  val: 1
```

`extension_config.yml`:
```yaml
default:
  dynaconf_include:
  - base_config.yml
  val: 2
```

If one now uses `extension_config.yml`, `val` will give `1` (the value defined in `base_config.yml`), while I would like it to give `2` instead (the value defined in `extension_config.yml`.

**Comment by rochacbruno** [comment]
in the current implementation Dynaconf does:

1. Read the provided `SETTINGS_FILE` in your case `extenson_config.yaml`
2. Load all the variables inside it {'dynaconf_include': [paths], 'val': 2}
3. Check the `dynaconf_include` if provided and read it
4. Load the dynaconf_include path and load variables {'val': 1}

https://dynaconf.readthedocs.io/en/latest/guides/usage.html#loading-order

The `include` is happening post the file load not respecting the exact order, and I think you are right, semantically the `include` should respect the order where it is declared.

Right now you can solve your specific problem with:

```py
from dynaconf import LazySettings

settings = LazySettings(
  PRELOAD_FOR_DYNACONF=["/path/*", "other/settings.toml"],    # <-- Loaded first
  SETTINGS_FILE_FOR_DYNACONF="/etc/foo/settings.py",          # <-- Loaded second (the main file)
  INCLUDES_FOR_DYNACONF=["other.module.settings", ... ]       # <-- Loaded at the end
)
```

https://dynaconf.readthedocs.io/en/latest/guides/advanced_usage.html#preloading-files

I'll mark this issue as a `bug` and I try to work on this soon, that will require some solution that can work for the variety of settings file formats we support.

**Comment by AndreasAlbert** [comment]
Thank you for this detailed explanation!

I followed your suggestion to try `PRELOAD_FOR_DYNACONF`, but I am having trouble understanding it entirely.

My configurations now look like this:

`base_config.yml`:
```yaml
default:
  val1: 1
  val2: 5
```


`extension_config.yml`:
```yaml
default:
  val1: 2
```


and I import them like this:
```python
settings = LazySettings(
  PRELOAD_FOR_DYNACONF=["base_config.yml"],    # <-- Loaded first
  SETTINGS_FILE_FOR_DYNACONF="extension_config.yml",          # <-- Loaded second (the main file)
  ENV_FOR_DYNACONF = "default",
  DYNACONF_WORKS="merge_configs",
  MERGE_ENABLED_FOR_DYNACONF=True
)
```

I now get the correct value of `val1`: 2. However, I cannot access `val2` anymore:
```shell
AttributeError: 'Settings' object has no attribute 'VAL2'
```
 With the merging settings I specified here, I was expecting to still be able to access `val2`. Is there a way to accomplish this?

**Comment by aberres** [comment]
I am having a similar issue.

I tried to use `dynaconf_include` in my `settings.toml` to separate really huge mapping dicts. At the same time I am trying to configure some of these mappings at runtime via redis.
As `dynaconf_include` is processed last - even when coming from the main settings file - the config from redis is nuked.
What is even more confusing: The setting is lost even when the includes just define `default` values while redis contains data for a specific environment.

An example:

```toml
# settings.toml
[default]
dynaconf_include = ["included.toml"]
inline = "from_file"

# included.toml
[default]
included = "from_file"
```

Set values to read from redis
    dynaconf write redis -v inline="from_redis" -v included="from_redis" -e production

When loaded I would naively expect the key `inline` and the key `included` both resolve to `from_redis`.

In practice this is the (unexpected) result:
```
$ dynaconf list -e production
Working in production environment
DYNACONF_INCLUDE: ['included.toml']
INLINE: 'from_redis'
INCLUDED: 'from_file'
```

If I would only set default values I could explain this with the loading order. Specific environment settings being lost not really. Even when a default value is set later in the loading order it should not alter environment specific settings, should it?

Personally I would love to see a way to get `dynaconf_include` stanzas in actual files to be handled as if the actual code would be placed directly in this file. Or maybe a different key should provide this feature?

**Comment by aberres** [comment]
FWIW now I finally realized (as described above) that I can solve my problem by defining `PRELOAD_FOR_DYNACONF` instead of `DYNACONF_INCLUDE`.
Works like a charm 🎊

**Comment by aberres** [comment]
But it is still not the ideal solution.

While `DYNACONF_INCLUDE` can be set from the main settings file itself, I have to ensure that `PRELOAD_FOR_DYNACONF` is set manually (by either settings the environment variable or manually configuring the settings object).

**Comment by rochacbruno** [comment]
Lots of things changed on 3.0.0 and this issue is still required

**Comment by rochacbruno** [comment]
This issue is added to 4.0.0 backlog, includes must be a loader feature part of #1150 
loaders will handle include individually,

I am closing this issue and referencing there
