### ISSUE TITLE
Improve the validators message [was] validator for ENV_FOR_DYNACONF

### ISSUE THREAD

**Issue by carlodri** [dynaconf/dynaconf#514]
I'm trying a very simple example with this validator:

```python
settings = Dynaconf(
    environments=True,
    settings_files=["settings.toml", ".secrets.toml"],
    validator=[Validator("ENV_FOR_DYNACONF", must_exist=True)],
)
```

since I would like to ensure that there is an explicit setting of the environment. But this doesn't seem to work, _i.e._ no exception is raised if that env variable is not set.

What am I missing here? By the way, I would further like to validate it with an `is_in` setting.

Thank you!

**Comment by rochacbruno** [comment]
```py
from dynaconf import Dynaconf, Validator

settings = Dynaconf(
    environments=True,
    settings_files=["settings.toml", ".secrets.toml"],
    validators=[
        Validator(
            "ENV_FOR_DYNACONF", 
            must_exist=True, 
            is_in=["foo", "bar"]
        )
    ],
)

settings.validators.validate()

```

```py
$ python app.py

dynaconf.validator.ValidationError: ENV_FOR_DYNACONF must is_in ['foo', 'bar'] but it is DEVELOPMENT in env DEVELOPMENT
```

then

```bash
/tmp via  v3.9.1 (tmp-b48853d32ee66e6) 
❯ export ENV_FOR_DYNACONF=foo

/tmp via  v3.9.1 (tmp-b48853d32ee66e6) 
❯ python app.py        
success!
```

**Comment by rochacbruno** [comment]
MIssing detail:

Validators are triggered on two situations:

1. manually called `settings.validators.validate()`

2. when the first access is made on settings `print(settings.SOMETHING)`

**Comment by carlodri** [comment]
Thanks, it works for me too!

I'm still confused as to this error message:
```

**Comment by carlodri** [comment]
by the way, I'm on Windows 10 if that can make a difference.

**Comment by rochacbruno** [comment]
This is fixed, now the default env is called `main` when not set, and we plan to improve validator messages tracked on https://github.com/dynaconf/dynaconf/issues/1082#issuecomment-2199703596

**Comment by carlodri** [comment]
Thank you @rochacbruno!
