### ISSUE TITLE
[bug (/docs?)] Validators are being run earlier than FORCE_ENV_FOR_DYNACONF can switch to testing env, thus, failing

### ISSUE THREAD

**Issue by Larleyt** [dynaconf/dynaconf#563]
**Describe the bug**
Currently, it seems not possible to use pytest fixture with `FORCE_ENV_FOR_DYNACONF` if the validators exist, due to validators run earlier and might fail.

Note, that in the app's codebase (as well as `tests/conftest.py`) I import config as:
```from mypkg.config import settings```
and not the 
```from dynaconf import settings```

Because it seems like validators will not be run at all if are imported the other way.
(What is the downside of such import and might that be a source of the subject's problem?)

Below is the complete example of the environment when the subject happens.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

# /mypkg/
# ...__init__.py...
# ...config.py...
# ...<other stuff>
# /tests/
# ...__init__.py...
# ...conftest.py/...
# ...test_010.py/...
# settings.toml
# .env
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**/.env**
```bash
MYPKG_ENV=production

<other non-python-app specific vars>
```

and

**/settings.toml**
```toml
[default]

[testing]
TMP_ROOT_DIR="/tmp/mypkg/tests"

[production]
# For production we'll just use [default] and some env vars from Dockerfile
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/mypkg/config.py**
```python
from dynaconf import Dynaconf, Validator

validators = [
    # Ensure some parameters exists (are required)
    Validator(
        "TMP_ROOT_DIR",
        must_exist=True,
    ),
]

settings = Dynaconf(
    validators=validators,
    envvar_prefix=False,
    settings_files=["settings.toml", ".secrets.toml"],
    environments=True,
    load_dotenv=True,
    env_switcher="MYPKG_ENV",
)
```

**conftest.py:**
```python
import pytest
from mypkg.config import settings

@pytest.fixture(scope="session", autouse=True)
def set_test_settings():
    """Forces usage of [testing] env from `settings.toml` for tests"""
    settings.configure(FORCE_ENV_FOR_DYNACONF="testing")
```
</details>

**Current behavior**
The `ValidationError` is raised before `settings.configure()` can be executed.

**Expected behavior**
To be able to use `settings.configure()` to actually switch the env and *then* run the validators

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Dynaconf Version 3.1.4
 - Frameworks in use: pytest

**Additional questions**
1. Is it okay to import settings directly from `config.py` and not from `dynaconf` module? Why the validators do not work when importing directly? Seems like a separate bug issue.
2. Are `[default]` settings implicitly inheritable? (Meaning everything that is not in `[production]` but in `[default]` will be available in `[production]` as well? Is that documented somewhere? Is there a switch to turn it on/off?)

**Comment by lingfish** [comment]
Yep, I've been banging my head against this one for days too.

And it seems that running `settings.validators.validate()` after the `settings.configure()` does nothing too, even though `settings.current_env` shows the right "FORCED" env.

**Comment by lingfish** [comment]
I've created a quick repo for this with a `pytest` action recreating the issue, @rochacbruno .

Test result [here](https://github.com/lingfish/dynaconf-issues-563/actions/runs/8012921606/job/21889103575)

**Comment by lingfish** [comment]
I also noticed this text in the docs:

> By default, if the data of an instance is updated with update, set or load_file methods, no validation will be triggered.

> You can override this globally with the option validate_on_update or set this on a per-call basis.

If I set either `validate_on_update=True` on instantiation, or as:

```python
@pytest.fixture(scope='session', autouse=True)
def set_test_settings():
    current_directory = os.path.dirname(os.path.realpath(__file__))
    settings.configure(FORCE_ENV_FOR_DYNACONF='testing',
                       VALIDATE_ON_UPDATE_FOR_DYNACONF=True
                       )
    settings.load_file(path=['proxmox_grapple_tests.yml'], silent=True, validate=True)
```

I get:

```python
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
```

Test result [here](https://github.com/lingfish/dynaconf-issues-563/actions/runs/8013366842/job/21890281500).

**Comment by pedro-psb** [comment]
I believe this might not be the right use for the `configure` method, because its recommended to be used for django context (by the docs, dont know much about this part of the implementation).

Anyway, I'll have a better look into this. Thanks for the providing rich context on the problem!

**Comment by lingfish** [comment]
Hi @pedro-psb, thanks for looking into it.

> I believe this might not be the right use for the configure method, because its recommended to be used for django context (by the docs, dont know much about this part of the implementation).

The [docs](https://www.dynaconf.com/advanced/#pytest) seem to indicate `configure` can be used with `pytest`; but I think it assumes you have one settings file, for both production and testing. I'm trying to make it load a testing-only settings file (as well as change running env as per this whole PR).

I'm trying to write a functional test to make sure my app catches validation errors and "does the right stuff", and right now, even with a intentionally-broken settings file, the tests are saying "all is well."

**Comment by pedro-psb** [comment]
I took a look and experimented with this:

## Observation

**1. deprecated global settings**
This global settings is deprecated since 3.0.0 (just so you know)

```python
from dynaconf import settings
```

**2. importing settings from other module**
That is not a problem if in the `config` module settings is instantiated with `Dynaconf` (not global `settings`), as it is in your examples:
```python
from config import settings # but config uses dynaconf.Dynaconf, not dynaconf.settings
```

**3. testing good pratices**
Not a good practice to import a module with side-effects (instatiating dynaconf, in this case) on the top-level of a test or conftest, because:
1. you loose control over how the instantiation should be setup.
2. you get poor test isolation as you have a mutable object in the wild (outside pytest fixtures world)

**4. documentation is out of date**
As for the observation about global `settings` deprecation, we can state that this section of the docs is really outdated. 

## Alternatives

I don't think there is any reason to try fixing this specific approach, as those are based on outdated docs. But there are some alternatives. 

### a) Explicit fixture

```python
import pytest


@pytest.fixture
def settings(monkeypatch):
    monkeypatch.setenv("ENV_FOR_DYNACONF", "testing")
    # load module here (in a controlled test environment)
    from config import settings as _settings
    return _settings


def test_running_on_testing_environment(settings):
    assert settings.current_env == "testing"
    assert settings.ENV_FOR_DYNACONF == "testing"

```

### b) Implicit fixture

```python
import os
from unittest import mock

import pytest


@pytest.fixture(scope="session", autouse=True)
def set_settings():
    # cant use monkeypatch with session-scoped fixtures
    with mock.patch.dict(os.environ, {"ENV_FOR_DYNACONF": "testing"}, clear=True):
        yield


def test_running_on_testing_environment():
    # load here instead of on the top-level
    # so we have control over the environ
    from config import settings

    assert settings.current_env == "testing"
    assert settings.ENV_FOR_DYNACONF == "testing"
```

## Outcomes

If those alternatives work for you, I think we can change this issue to a `docs issue` and replace the recommended approach to setup pytest without a framework.

Please, let me know what you think!

**Comment by lingfish** [comment]
I'll preface this by saying I'm not sure if you're replying at me, or at @Larleyt, but will assume me.

> I took a look and experimented with this:
> 
> ## Observation
> **1. deprecated global settings** This global settings is deprecated since 3.0.0 (just so you know)

Understood, I'm not using it that way.

> **2. importing settings from other module** That is not a problem if in the `config` module settings is instantiated with `Dynaconf` (not global `settings`), as it is in your examples:

Sorry, who's examples?  I'm not seeing it used that way in [my examples](https://github.com/lingfish/dynaconf-issues-563/blob/main/config.py#L1)...

> ```python
> from config import settings # but config uses dynaconf.Dynaconf, not dynaconf.settings
> ```

Sorry, your code comment here contradicts your first statement above?

> **3. testing good pratices** Not a good practice to import a module with side-effects (instatiating dynaconf, in this case) on the top-level of a test or conftest, because:
> 
> 1. you loose control over how the instantiation should be setup.
> 2. you get poor test isolation as you have a mutable object in the wild (outside pytest fixtures world)

Or, is it a design flaw that nothing should really happen at instantiation until the code is asked to do something?

I mean, there is the ability to [lazy validate](https://www.dynaconf.com/validation/#lazy-validation), but then loading the validators is a little tricky too.

In my experimentation, it seems that Dynaconf lazily executes the validation (even when configuring right at instantiation), seemingly waiting until the `settings` instance is first accessed.  This goes against [this part of the doco](https://www.dynaconf.com/validation/#on-instantiation).
 
> **4. documentation is out of date** As for the observation about global `settings` deprecation, we can state that this section of the docs is really outdated.

:+1: 

> ## Alternatives
> I don't think there is any reason to try fixing this specific approach, as those are based on outdated docs. But there are some alternatives.
> 
> ### a) Explicit fixture

An interesting approach, and similar to how I've fixed it "for now".  I merely don't run my fixture setup code at all, and just use this in my `tox.ini`:

```ini
set_env =
    FORCE_ENV_FOR_DYNACONF = testing
    SETTINGS_FILE_FOR_DYNACONF = tests/proxmox_grapple_tests.yml
```

> ### b) Implicit fixture

Yeah, very convoluted though, no?

> If those alternatives work for you, I think we can change this issue to a `docs issue` and replace the recommended approach to setup pytest without a framework.

Not sure what you mean about "framework".

Overall, I still don't feel like any of this is clean.

**Comment by pedro-psb** [comment]
Thanks for the feedback.
I was referring to both examples, as they are similar in general. But I was hoping that you would answer, as this issue is pretty old.

---

> Sorry, who's examples? I'm not seeing it used that way in [my examples](https://github.com/lingfish/dynaconf-issues-563/blob/main/config.py#L1)...

Sorry, this section came out pretty confusing. I meant that your example is ok.

---

About the validation behavior, the docs is wrong again, we need to fix it. The validation is triggered upon access.

And I believe I found the reason why validation was being fired early. The importing `from config import settings` did nothing special by itself, but Pytest does some inspecting on the test files on the test collection process, and that was accessing the imported (lazy) `settings` and firing the validation. So again, IMO the solution for that is proper isolating the instantiation/import.

---

> b) Implicit fixture

Yeah, I prefer a), but who knows.

---

> Not sure what you mean about "framework".

Sorry, "webapp" frameworks: Django, Flask or FastApi. There might be specific test setups for those.

---

> Overall, I still don't feel like any of this is clean.

I like option `a)`, but it would be nice to hear how do you think could be a clean way. Maybe we can investigate if we can support that.

**Comment by lingfish** [comment]
> Sorry, this section came out pretty confusing. I meant that your example is ok.

All good!

> About the validation behavior, the docs is wrong again, we need to fix it. The validation is triggered upon access.
> 
> And I believe I found the reason why validation was being fired early. The importing `from config import settings` did nothing special by itself, but Pytest does some inspecting on the test files on the test collection process, and that was accessing the imported (lazy) `settings` and firing the validation. So again, IMO the solution for that is proper isolating the instantiation/import.

Or... option C... why not a new kwarg to `settings.configure` to disable early/lazy validation?  And then the user has to explicitly call `settings.validators.validate()`?  A bit like how the doco states you can configure validators later on?

Or would the kwarg to `settings.configure` already be too late?

> Yeah, I prefer a), but who knows.

Me too, thus far, in lieu of anything else.  I'm just with oldschool Python that (used to? still does?) say good practice isn't to import anywhere but at the top of your code.

> I like option `a)`, but it would be nice to hear how do you think could be a clean way. Maybe we can investigate if we can support that.

Although the lazy validation triggered at first access is "cute", I also think it's a bit of magic/voodoo that introduces more complexity and confusion.  I personally wouldn't expect a library to do almost anything in import, or on first access.

I feel validations should always be explicitly requested.  User configures the settings, validators etc, and then needs to "click start" so to speak.  Having code raise an exception before that time also makes it weirder/harder to catch.

1. `settings` done in a `config.py`
2. Main code imports settings
3. Main code does other stuff, setup logging, `click` stuff, etc
4. Then finally, a simple:
```python
try:
    settings.validators.validate()
except ValidationError as e:
    click.echo(e, err=True)
    sys.exit(1)
```

A kwarg could also ease migration by defaulting to existing behaviour and not breaking code already out there.

**Comment by pedro-psb** [comment]
> Or... option C... why not a new kwarg to settings.configure to disable early/lazy validation? And then the user has to explicitly call settings.validators.validate()? A bit like how the doco states you can configure validators later on?
> 
> Or would the kwarg to settings.configure already be too late?

I guess not, your idea should be doable. But you can configure validations later [with this](https://www.dynaconf.com/validation/#lazy-validation) approach and make an explicit call to validate. I'm not sure if I follow your motivation.

---

About your idea of making things more explicit, I'm in favor of that. I'm a relatively new maintainer of this project, but from what I've experienced and understood about the codebase so far, this idea of triggering things upon access is not just some personal flavor, it probably has to do with the integration with web frameworks, specially django. Django doesn't provide a clean way to customize their settings, and due to its long-living-webserver nature, sometimes it's pretty challenging to support integration with them.

But yeah, your idea sounds good and reasonable, thanks for sharing it!

**Comment by lingfish** [comment]
> > Or... option C... why not a new kwarg to settings.configure to disable early/lazy validation? And then the user has to explicitly call settings.validators.validate()? A bit like how the doco states you can configure validators later on?
> > Or would the kwarg to settings.configure already be too late?
> 
> I guess not, your idea should be doable. But you can configure validations later [with this](https://www.dynaconf.com/validation/#lazy-validation) approach and make an explicit call to validate. I'm not sure if I follow your motivation.

My motivation is being explicit I guess.  I kinda personally feel the lazy validation method linked above is more of this "magic" I've mentioned.  I think configuring the validators using the `config.py settings = Dynaconf()` model keeps most of Dynaconf in one place, is clean, and then you can (optionally) validate when *you* want to, not when magically first accessed.

It of course takes away any magic for functional/integration testing.

> About your idea of making things more explicit, I'm in favor of that. I'm a relatively new maintainer of this project, but from what I've experienced and understood about the codebase so far, this idea of triggering things upon access is not just some personal flavor, it probably has to do with the integration with web frameworks, specially django. Django doesn't provide a clean way to customize their settings, and due to its long-living-webserver nature, sometimes it's pretty challenging to support integration with them.

Copy that, understood.  A good idea then, if my idea is implemented, to default to the existing behaviour ;)

> But yeah, your idea sounds good and reasonable, thanks for sharing it!

:+1:

**Comment by wgordon17** [comment]
Just wanted to add in that _this_ doc (https://www.dynaconf.com/django/#using-pytest-and-django) is no longer working for me.

```
test setup failed
@pytest.fixture(scope="session", autouse=True)
    def _force_test_settings():
        # https://github.com/dynaconf/dynaconf/issues/491#issuecomment-745391955
        from django.conf import settings
    
>       settings.setenv("testing")

../conftest.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.venv/lib/python3.9/site-packages/dynaconf/base.py:833: in setenv
    self.execute_loaders(env=env, silent=silent, filename=filename)
../../.venv/lib/python3.9/site-packages/dynaconf/base.py:1191: in execute_loaders
    execute_instance_hooks(self, "post", self._post_hooks)
../../.venv/lib/python3.9/site-packages/dynaconf/loaders/__init__.py:94: in execute_instance_hooks
    _run_hook_function(obj, hook_type, hook_func, hook_source)
../../.venv/lib/python3.9/site-packages/dynaconf/loaders/__init__.py:186: in _run_hook_function
    hook_dict = hook_func(obj.dynaconf.clone())
../../.venv/lib/python3.9/site-packages/dynaconf/base.py:1379: in dynaconf_clone
    return copy.deepcopy(self)
/Users/wgordon/.rye/py/cpython@3.9.18/install/lib/python3.9/copy.py:172: in deepcopy
    y = _reconstruct(x, memo, *rv)
/Users/wgordon/.rye/py/cpython@3.9.18/install/lib/python3.9/copy.py:270: in _reconstruct
    state = deepcopy(state, memo)
/Users/wgordon/.rye/py/cpython@3.9.18/install/lib/python3.9/copy.py:146: in deepcopy
    y = copier(x, memo)
/Users/wgordon/.rye/py/cpython@3.9.18/install/lib/python3.9/copy.py:230: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
/Users/wgordon/.rye/py/cpython@3.9.18/install/lib/python3.9/copy.py:153: in deepcopy
    y = copier(memo)
../../.venv/lib/python3.9/site-packages/dynaconf/vendor/box/box.py:112: in __deepcopy__
    for(F,G)in A.items():C[copy.deepcopy(F,B)]=copy.deepcopy(G,B)
../../.venv/lib/python3.9/site-packages/dynaconf/vendor/box/box.py:117: in items
    def items(A):return[(B,A[B])for B in A.keys()]
../../.venv/lib/python3.9/site-packages/dynaconf/vendor/box/box.py:117: in <listcomp>
    def items(A):return[(B,A[B])for B in A.keys()]
../../.venv/lib/python3.9/site-packages/dynaconf/utils/boxing.py:26: in evaluate
    return recursively_evaluate_lazy_format(value, settings)
../../.venv/lib/python3.9/site-packages/dynaconf/utils/__init__.py:424: in recursively_evaluate_lazy_format
    return _recursively_evaluate_lazy_format(value, settings)
../../.venv/lib/python3.9/site-packages/dynaconf/utils/__init__.py:432: in _recursively_evaluate_lazy_format
    value = value(settings)
../../.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py:234: in __call__
    result = self.formatter(self.value, **self.context)
../../.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py:151: in __call__
    return self.function(value, **context)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

B = <BoxList: []>, item = 0

    def __getitem__(B,item):
    	A=item
    	if B.box_options.get(_G)and isinstance(A,str)and A.startswith('['):
    		C=_list_pos_re.search(A);D=super(BoxList,B).__getitem__(int(C.groups()[0]))
    		if len(C.group())==len(A):return D
    		return D.__getitem__(A[len(C.group()):].lstrip('.'))
>   	return super(BoxList,B).__getitem__(A)
E    IndexError: list index out of range

../../.venv/lib/python3.9/site-packages/dynaconf/vendor/box/box_list.py:34: IndexError
```

**Comment by rochacbruno** [comment]
maybe this one is also fixed by calling .reload() ? we need to test it more.

If this becomes an **impossible** to fix issue we must mark as a known-caveat on the django docs and close the issue

**Comment by rochacbruno** [comment]
#1157 will change how multiple environments work and must address this issue
