### ISSUE TITLE
[bug] __resolve_config_aliases might corrupt correct params

### ISSUE THREAD

**Issue by abcdenis** [dynaconf/dynaconf#593]
Hi,
I suddenly read dynaconf sources and found out that `dynaconf.base.LazySettings.__resolve_config_aliases` might corrupt settings passed to it. Look:

```
# user code
cfg = LazySettings(settings_file='AAA', settings_files='BBB')

# kwargs after applying __resolve_config_aliases()
{'settings_file': 'BBB'}
```

Misspeling correction is awful because Python has clear way to define and check parameter names:
```
def __init__(self, settings_file: Optional[str] = None, **kwargs):
  ...
``` 
then you will be able to push them into kwargs and pop misspelled names out of it (as you prefer to handle parameters as dictionary).

One could alter misspelling test on https://github.com/rochacbruno/dynaconf/blob/master/tests/test_base.py#L893
to 
```
settings = LazySettings(settings_file="settings.toml", settings_files="my-custom.toml")
```
Now there is correct parameter which will be broken by misspelling autofix feature.

**Comment by rochacbruno** [comment]
Not fixing this because in 4.0.0 we are going to change how settings _files are defined, the variable singular settings_file will be removed. 

ref #1150 #1156
