### ISSUE TITLE
[RFC] add a core loader for given overrides

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [dynaconf/dynaconf#610]
**Is your feature request related to a problem? Please describe.**

when writing tests i want to create configured instances that are given overrides
we use dynaconf merging and deep merging excessively and the default `for_env` cant providethat

**Describe the solution you'd like**

```python
settings_with_changes = settings.for_env( ....overrides={"hostname", ...", ....}), 
```

**Describe alternatives you've considered**

* manually merging the config -> error prone
* implementing a own loader and making new config instances -> also error prone

**Additional context**not publicly available, can be shared if necessary

**Comment by rochacbruno** [comment]
Have you tried this?

```py
from dynaconf import Dynaconf

settings = Dynaconf(
    version="1",
    name="foo"
)


assert settings.version == "1"
assert settings.name == "foo"


new_settings = settings.from_env(version="2", keep=True)


assert new_settings.version == "2"
assert new_settings.name == "foo"
```

**Comment by rochacbruno** [comment]
https://www.dynaconf.com/advanced/#from_env

**Comment by RonnyPfannschmidt** [comment]
@rochacbruno im using deep merges/overrides, the from_env method does a direct update of the kwargs 

```ipy
In [1]: import dynaconf

In [2]: settings = dynaconf.Dynaconf(users=dict(test=dict(username="a", password="b")))

In [3]: settings = settings.from_env(users=dict(test=dict(password="v")))

In [4]: settings.as_dict()
Out[4]: 
{'USERS': {'test': {'password': 'v'}},

**Comment by rochacbruno** [comment]
Yes,

If you need a merge you would need `keep` and `dynaconf_merge` 

```py
settings = dynaconf.Dynaconf(users=dict(test=dict(username="a", password="b")))

settings = settings.from_env(
    users=dict(test=dict(password="v"), dynaconf_merge=True),
    keep=True
)
```

OR, enable the Global merge.

```py
settings = dynaconf.Dynaconf(
    users=dict(test=dict(username="a", password="b")),
    merge_enabled=True   # global merge
)

settings = settings.from_env(
    users=dict(test=dict(password="v")),
    keep=True
)
```

Looks like we need a more explicit option such as


```py
settings.clone_and_merge(**data)
```

The above would take care of adding `keep=True` and marking the data to be merged.
