### ISSUE TITLE
[RFC] provide a way to override the core loaders as objects

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [dynaconf/dynaconf#612]
**Is your feature request related to a problem? Please describe.**

currently the core loaders that get called for all the settings files
are configured by a select/deselect list of strings
this makes configuring loaders tricky 

my personal use case is wanting to reconfigure the yaml loader (#611) and adding a overrides loader (#610)

**Describe the solution you'd like**

```
settings = Settings(CORE_LOADERS_FOR_DYNACONF=[custom_yaml_loader])
```

**Describe alternatives you've considered**
monkeypatching, its terrifying

**Comment by rochacbruno** [comment]
This is easy to fix,

We can change the hardcoded `loaders = {}` on the `loaders/__init__` with a call to `obj.get_core_loaders` inside that method we look for the `CORE_LOADERS` value.

**Comment by fechnert** [comment]
This would be great to have, as you could inject a custom core loader to load secrets, which you could then use in the settings files as a reference.
