### ISSUE TITLE
[RFC] utilities to get raw items from dynaconf/dynabox

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [dynaconf/dynaconf#615]
**Is your feature request related to a problem? Please describe.**
currently lazy objects are always evaluated, thats a problem for merges and introspection

**Describe the solution you'd like**

```pycon
>>> settings.get_raw("users.magical")
LazyLoadedUser("magical")
```

**Describe alternatives you've considered**
monkeypatching the evaluator

**Comment by rochacbruno** [comment]
The `raw` version of evaluated fields are kept under `settings.raw_{fieldname}`  

https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/utils/boxing.py#L21 

Maybe we need a better way to fetch it.

**Comment by RonnyPfannschmidt** [comment]
its in particular tricky for deep values, having a method to call on the box to do a get raw would be a great help

**Comment by RonnyPfannschmidt** [comment]
also the raw value currently is stored incorrectly using a tag to undo the formatter transformation, it breaks other lazy objects
