### ISSUE TITLE
[RFC] Support typing annotations on Schema

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#679]
This is a placeholder issue for the schema feature that is coming on 4.0 #677

**Comment by eugene-prout** [comment]
This looks like a great feature. The work in #677 is from a while ago, just wondering if this is still on the roadmap? Thank you

**Comment by eugene-prout** [comment]
That looks amazing, will keep a close eye on it as it develops. Thanks for the reply 👍

**Comment by q-wertz** [comment]
Is this replaced by https://github.com/dynaconf/dynaconf/issues/1104 or are those distinct features?
