### ISSUE TITLE
[RFC] Upgrade TOML library to TOML 1.0.0

### ISSUE THREAD

**Issue by FrankBattaglia** [dynaconf/dynaconf#708]
**Is your feature request related to a problem? Please describe.**
I would like to use features of the TOML 1.0.0 specification, but the current vendored library is only compatible with v0.5.0

**Describe the solution you'd like**Update the vendored library to one that is compatible with TOML 1.0.0.  See e.g. https://github.com/toml-lang/toml/wiki#v100-compliant

**Describe alternatives you've considered**
Don't use v1.0.0 features, which makes the TOML file less expressive

**Additional context**
(specifically, mixed-type arrays)

**Comment by rochacbruno** [comment]
https://github.com/dynaconf/dynaconf/pull/798
