### ISSUE TITLE
How to use dynaconf in pytest when declared custom settings object

### ISSUE THREAD

**Issue by mzebrak** [dynaconf/dynaconf#728]
Hi. I need to override the environment for settings in conftest.py. As I found I can do it by adding:

```python
from dynaconf import settings


@pytest.fixture(scope="session", autouse=True)
def set_test_settings():
    settings.configure(FORCE_ENV_FOR_DYNACONF="testing")
```

but in my case I' ve got my own settings object under in the `confg.py` module and it looks like this:
```python
settings = Dynaconf(
    envvar_prefix='MY_PREFIX',
    settings_files=['settings.toml', '.secrets.toml'],
    environments=True,
    env_switcher='ENVIRONMENT_NAME',
)
```

and when I'm trying to do 

```python
from config import settings


@pytest.fixture(scope="session", autouse=True)
def set_test_settings():
    settings.configure(FORCE_ENV_FOR_DYNACONF="testing")
```

it does not work. It only overrides settings imported directly from dynaconf module. This is a problem because in my app I'm using settings from my `config.py` and my tests are failing when I override settings from `dynaconf` and use `from dynaconf import settings` in tests - because in app I'm using `from config import settings`

**Comment by rochacbruno** [comment]
Fixed and added a test https://github.com/dynaconf/dynaconf/pull/809/files
