### ISSUE TITLE
[RFC] Allow to fallback to unprefixed environment variable when value not found. was [Question] Using dynaconf, how would I go about getting the well known environment Linux variable "PATH"?

### ISSUE THREAD

**Issue by gc-ss** [dynaconf/dynaconf#742]
If I just wanted to get the well known environment Linux variable `PATH`, how should I fetch it using dynaconf?

I tried:

`settings.get('PATH', 'Noooope')`

and always get `Noooope`

I am hoping for a behavior similar to `os.environ["PATH"] ` but with all the (optional) dynaconf goodness, if they are present

**Comment by rochacbruno** [comment]
https://github.com/rochacbruno/dynaconf/blob/b3aff91da5a17a6e4646d439e3477bb4d21369bf/dynaconf/base.py#L465-L481

```py
settings.get_environ("PATH", "Noooper")

```

**Comment by gc-ss** [comment]
@rochacbruno I really appreciate you taking your time to read the details and helping me out! I don't know why I couldn't find this detail earlier and I tried to read the docs, look at the examples and Google as well.

I am assuming `get_environ` also supports dynaconf goodness, if they are present eg:

Setting `DYNACONF_PATH` would override the system `PATH` inside the dynaconf `settings`?

**Comment by rochacbruno** [comment]
I think the idea of this issue is to provide an API to get a value from settings and fallback to envvars.

To be implemented.

```py
from dynaconf import Dynaconf

settings = Dynaconf(
	fallback_to_environ=True,
	fallback_to_environ=["PATH", ...],
)

print(settings.PATH)
# if not available on `settings` would fallback to `get_environ` and follow all the dynaconf formatting etc...

```

Right now the workaround is.

```py
settings.get("PATH", default=settings.get_environ("PATH"))
```

**Comment by rochacbruno** [comment]
One thing to notice is that you can set `envvar_prefix=False` and then dynaconf will read all the environment variables from your system.
