### ISSUE TITLE
[docs] Pyinstaller Compiles the Dynaconf Modules and loaders so when _dynaconf.loader.py_loader_ tries to load files from the inspect stack trace it tries to read compiled pyc files and fails on UnicodeDecodeError. The fix is to pacakage dynaconf and python-dotenv[cli] as a package without compiling it by using the **--collect-all** argument of pyinstaller

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#792]
Pyinstaller Compiles the Dynaconf Modules and loaders so when _dynaconf.loader.py_loader_ tries to load files from the inspect stack trace it tries to read compiled pyc files and fails on UnicodeDecodeError. The fix is to pacakage dynaconf and python-dotenv[cli] as a package without compiling it by using the **--collect-all** argument of pyinstaller

_Originally posted by @OmmarShaikh01 in https://github.com/dynaconf/dynaconf/issues/770#issuecomment-1193254565_

**Comment by pedro-psb** [comment]
Closed (as it is labeled as docs) by #899 
Related to this other packaging dynaconf issue #902
