### ISSUE TITLE
Why does changing root_path not change the root for files set in settings_files?

### ISSUE THREAD

**Issue by jacobthetechy** [dynaconf/dynaconf#812]
I have had issues when trying to use cx_freeze with dynaconf. And every time it is fixed buy passing absolute file paths for files specified in `preload`, `settings_files`, and `includes`. I've recently tried to use `root_path` to properly set the root for all the files specified in `preload`, `settings_files`, and `includes`. I have found that fixes the need to have absolute file paths for `preload` and `includes` but does not add the specifies root to `settings_files`. It will search in several places instead.

Example:
```python
from dynaconf import Dynaconf

settings = Dynaconf(
    root_path='D:/',                # Ensure that root is proper location
    preload='base.toml',            # Looks for: 'D:/base.toml'
    settings_files='machine.toml',  # Looks for 'machine.toml' in: ['D:\\', 'D:\\config', 'G:\\Projects\\cx_freeze-dynaconf', 'G:\\Projects\\cx_freeze-dynaconf\\config', 'G:\\Projects', 'G:\\Projects\\config', 'G:\\', 'G:\\config']
    includes='local.toml',          # Looks for 'D:/local.toml'
)
```

I am getting the file names from [dynaconf.utils.find_file()](https://github.com/dynaconf/dynaconf/blob/d15602239b006dfef7957d2cb55277ba743f1052/dynaconf/utils/files.py#L36) by adding a `print(f'{filename=}')` to the beginning of the function and `print(f'{search_tree=}')` [on line 72](https://github.com/dynaconf/dynaconf/blob/7836bd553cc8f919b73016ff47baa24c63a662b5/dynaconf/utils/files.py#L72) of the same function.

Is this intended behavior? If so why add the root to `preload` and `includes` but not `settings_files`?

Thanks

**Comment by rochacbruno** [comment]
This is the expected,

The preload and includes must be strict, but the settings_files will build a search tree and find the files recursivelly until a match is found, from the pwd to the root_dir

**Comment by rochacbruno** [comment]
we need better docs around it

**Comment by jacobthetechy** [comment]
If this needs to be in a new issue I don't mind making one.
