### ISSUE TITLE
Aliased variables : Is it possible to map 2 names to the same variable ?

### ISSUE THREAD

**Issue by Wenzel** [dynaconf/dynaconf#836]
Hi,

I was wondering if it was possible to associate 2 names like `reload` and `snapshot_reload` to the same variable in Dynaconf ?
So that we can conduct a deprecation management by introducing a new configuration setting mapped to the old name, and remove the old name when we feel like it.

Is it natively supported ?
I skimmed through the docs but only found the `Validators(*names)` which is not what I'm looking for.

Is there a way this could be supported (or a hack around Validators for the time being ?) ?

Thanks !

**Comment by rochacbruno** [comment]
Right now the only way is using a lazy formatting 

```
RELOAD = "@int @format {this[SNAPSHOT_RELOAD]}"
```

Also `@jinja` is available if you need more templating features.

Someone else suggested and alias feature that may be implemented in a future version and will work like

```
# NotImplementedYet
settings = Dynaconf(
     aliases={"reload": ["snapshot_reload"]}
)
```

**Comment by rochacbruno** [comment]
There is now the get feature #650 and #1137
