### ISSUE TITLE
[RFC] Ability to add custom error message for Validator

### ISSUE THREAD

**Issue by iTaybb** [dynaconf/dynaconf#849]
**Is your feature request related to a problem? Please describe.**
Currently, when using a Validator with a custom condition, the error message is not indicative enough.

For example:
`Validator("ipify_api_list", condition=lambda x: len(x) > 5)`
would result in:
`dynaconf.validator.ValidationError: ipify_api_list invalid for <lambda>(['api.ipify.com']) in env main`

**Describe the solution you'd like**
Add a new, "error_msg" option for Validator that will be shown as the error message

**Additional context**
I'll be glad to make a PR for this myself.

**Comment by iTaybb** [comment]
This is true (however the key of the `messages` should be `condition` and not `operations`.
So this issue is about documenting it better :)

**Comment by rochacbruno** [comment]
added to the docs
