### ISSUE TITLE
[bug] dynaconf is not installable in venvs without setuptools

### ISSUE THREAD

**Issue by jaklan** [dynaconf/dynaconf#851]
### Bug description

`dynaconf` doesn't define any dependencies (due to vendoring), but that's not really true, because there is one runtime dependency - `pkg_resources` distributed with `setuptools`:
https://github.com/dynaconf/dynaconf/blob/0439bf836f1a22e96e4c71d388c2e68fd9b70425/dynaconf/contrib/flask_dynaconf.py#L17

How is it possible that it actually works? Only thanks to a "de facto" standard of pre-installing `setuptools` a) together with Python interpreter b) when [creating virtual environments](https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-virtual-environments):
>[venv](https://docs.python.org/3/library/venv.html) is available by default in Python 3.3 and later, and installs [pip](https://packaging.python.org/en/latest/key_projects/#pip) and [setuptools](https://packaging.python.org/en/latest/key_projects/#setuptools) into created virtual environments in Python 3.4 and later.
>
>[virtualenv](https://packaging.python.org/en/latest/key_projects/#virtualenv) needs to be installed separately, but supports Python 2.7+ and Python 3.3+, and [pip](https://packaging.python.org/en/latest/key_projects/#pip), [setuptools](https://packaging.python.org/en/latest/key_projects/#setuptools) and [wheel](https://packaging.python.org/en/latest/key_projects/#wheel) are always installed into created virtual environments by default (regardless of Python version).

It means `setuptools` was not explicitly declared, but it was assumed it would be there anyway. But as I mentioned - it never was a real standard and it caused serious issues in the Python build system as precisely described in [PEP 518](https://peps.python.org/pep-0518/#rationale):
>But when a project chooses to use setuptools, the use of an executable file like setup.py becomes an issue. You can’t execute a setup.py file without knowing its dependencies, but currently there is no standard way to know what those dependencies are in an automated fashion without executing the setup.py file where that information is stored. It’s a catch-22 of a file not being runnable without knowing its own contents which can’t be known programmatically unless you run the file.

And that's why `PEP 518` introduced the [build-system table](https://peps.python.org/pep-0518/#build-system-table) defined in `pyproject.toml`:
```
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
```
Thanks to that and [PEP 517](https://peps.python.org/pep-0517/) - package managers know what are the actual build dependencies and how they should be handled. What does it imply? No need to blindly install `setuptools` anymore.

Based on that `poetry` introduced a flag [`virtualenvs.options.no-setuptools`](https://python-poetry.org/docs/configuration/#virtualenvsoptionsno-setuptools), which is currently disabled by default, but generally recommended:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/24907857/210487739-354f7b1c-7a70-4853-8c1d-69aab3444644.png">

What's the implication of the above? Well, I guess you already know:
```shell
❯ poetry config --local virtualenvs.options.no-setuptools true
❯ poetry add dynaconf
❯ poetry run python -c "from dynaconf.contrib.flask_dynaconf import DynaconfConfig"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lanskij/Repositories/dyna/.venv/lib/python3.10/site-packages/dynaconf/__init__.py", line 5, in <module>
    from dynaconf.contrib import DjangoDynaconf  # noqa
  File "/Users/lanskij/Repositories/dyna/.venv/lib/python3.10/site-packages/dynaconf/contrib/__init__.py", line 4, in <module>
    from dynaconf.contrib.flask_dynaconf import DynaconfConfig  # noqa
  File "/Users/lanskij/Repositories/dyna/.venv/lib/python3.10/site-packages/dynaconf/contrib/flask_dynaconf.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Required fixes

- **package building**

  As showed above - we can't assume anymore `setuptools` would be **for sure** pre-installed in given environment. That's why a proper definition of build dependency should be added to `pyproject.toml`:
  ```toml
  [build-system]
  requires = ["setuptools"]
  build-backend = "setuptools.build_meta"
  ```
  
  PS The current usage of `setup_requires` in `setup.py` is redundant, it's even mentioned directly in `PEP 518`:
  > Setuptools tried to solve this with a setup_requires argument to its setup() function [[3]](https://peps.python.org/pep-0518/#setup-args). This solution has a number of issues, such as:
  > - This cannot include setuptools itself nor can it include a replacement to setuptools, which means that projects such as numpy.distutils are largely incapable of utilizing it and projects cannot take advantage of newer setuptools features until their users naturally upgrade the version of setuptools to a newer one.
  
- **package runtime**

   Here we have 3 solutions:
   - specify `setuptools` as a package dependency
   - vendor `setuptools` 
   - get rid of `setuptools`- and `pkg_resources`-related runtime logic at all
   
   Personally - I would vote for the last one. Looking quickly - there's exactly one such line, which is:
https://github.com/dynaconf/dynaconf/blob/0439bf836f1a22e96e4c71d388c2e68fd9b70425/dynaconf/contrib/flask_dynaconf.py#L226
   That was probably copy-pasted from the `flask` codebase. But `flask` maintainers already fixed that on their side in https://github.com/pallets/flask/issues/4419 and switched to the built-in `importlib.metadata`, so when aligned - there would be also no need for `dynaconf` to depend on `setuptools` in runtime anymore.

**Comment by rochacbruno** [comment]
Thanks @jaklan in fact we need to migrate to the proper usage of `pyproject.toml` so this must be covered on this migration.

**Comment by astrojuanlu** [comment]
Furthermore, dynaconf should look for an alternative to `pkg_resources`:

```
File /metrics-test/.env/lib/python3.10/site-packages/dynaconf/__init__.py:5
      3 from dynaconf.base import LazySettings  # noqa
      4 from dynaconf.constants import DEFAULT_SETTINGS_FILES
----> 5 from dynaconf.contrib import DjangoDynaconf  # noqa
      6 from dynaconf.contrib import FlaskDynaconf  # noqa
      7 from dynaconf.validator import ValidationError  # noqa

File /metrics-test/.env/lib/python3.10/site-packages/dynaconf/contrib/__init__.py:4
      1 from __future__ import annotations
      3 from dynaconf.contrib.django_dynaconf_v2 import DjangoDynaconf  # noqa
----> 4 from dynaconf.contrib.flask_dynaconf import DynaconfConfig  # noqa
      5 from dynaconf.contrib.flask_dynaconf import FlaskDynaconf  # noqa

File /metrics-test/.env/lib/python3.10/site-packages/dynaconf/contrib/flask_dynaconf.py:17
     13     Config = object
     16 import dynaconf
---> 17 import pkg_resources
     20 class FlaskDynaconf:
     21     """The arguments are.
     22     app = The created app
     23     dynaconf_args = Extra args to be passed to Dynaconf (validator for example)
   (...)
     78 
     79     """

File /metrics-test/.env/lib/python3.10/site-packages/pkg_resources/__init__.py:121
    117 _namespace_handlers = None
    118 _namespace_packages = None
--> 121 warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
    124 _PEP440_FALLBACK = re.compile(r"^v?(?P<safe>(?:[0-9]+!)?[0-9]+(?:\.[0-9]+)*)", re.I)
    127 class PEP440Warning(RuntimeWarning):

DeprecationWarning: pkg_resources is deprecated as an API
```

Currently, the recommended option is `importlib.metadata` and its backport `importlib_metadata`:

https://docs.python.org/3/library/importlib.metadata.html#entry-points

May I open another issue about this?
