### ISSUE TITLE
[bug] Dynaconf not parsing multiline toml tables

### ISSUE THREAD

**Issue by lainiwa** [dynaconf/dynaconf#855]
**Describe the bug**
TOML standard updated May 2022 to include multi-line tables ([issue](https://github.com/toml-lang/toml/issues/516)).
This standard is not supported by the toml library dynaconf uses, as it was last updated ~2y ago.

**To Reproduce**
Try to read this this settings.toml:
```toml
[default]
point = {
  x = 1,
  y = 2,
}
```
Dynaconf fails to read this config.

**Environment (please complete the following information):**
 - OS: Ubuntu22.04
 - Dynaconf Version 3.1.11

**Additional context**
I guess it is best to consider moving to an alternative toml library (e.g. poetry uses tomli+tomlkit: [link](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L71)).

**Comment by pedro-psb** [comment]
According to the [changelog](https://github.com/toml-lang/toml/blob/main/CHANGELOG.md), "Allow newline after key/values in inline tables." it is still unreleased. 

I've quickly tested both tomlkit and tomli and they still do not support this syntax.
I would prefer multiline too, but I guess we'll have to wait.
