### ISSUE TITLE
seting config through env varaible

### ISSUE THREAD

**Issue by gunjan075** [dynaconf/dynaconf#860]
Hi,
In my settings.toml i have a varaible ref_date="'2023-01-31'". =====>WORKING
Now when i do export mypref_ref_date="'2023-01-31'" it is not working  =====>NOT WORKING

**Comment by rochacbruno** [comment]
![2023-02-13_15-30](https://user-images.githubusercontent.com/458654/218500761-d69a3c86-ecb3-4cae-b294-358be396b619.png)

**Comment by rochacbruno** [comment]
This is currently not a bug, but we miss a notice on https://www.dynaconf.com/envvars/ that dynaconf loader will only look for uppercase prefixed envvars.

OR... we might need to change the implementation on env_loader to start looking for lowercase env vars too.

This design choice was made in the beggining of the project but probably can be changed now.
