### ISSUE TITLE
[bug] Not merging sublevel configurations correctly

### ISSUE THREAD

**Issue by yarinbar** [dynaconf/dynaconf#863]
I need to switch between debugging and regular run profile and really wish to avoid using environment settings rather i want to use inline argument to my program to switch.

In `default.yaml` I have:
```yaml
SETTINGS:
   RUN_WITH_SEED: false
   SEED: 42

   COLORS: ['red', 'white']
```

And in my `debug.yaml` I have only:
```yml
SETTINGS:
   RUN_WITH_SEED: true
```

However, when I load the debug after the default it also removes the untouched settings. I really want to avoid writing all settings again because most are unchanged and there are quite a few.

This is how I load them:

```python
import argparse
args = parse_args()
config_files = ['config/default.yaml', 'config/.secrets.yaml']

if args.debug:
    config_files.append('config/debug.yaml')

config = Dynaconf(
        envvar_prefix="DYNACONF",
        settings_files=config_files,
)

print(config.SETTINGS.COLORS)

```

Yields:

```
"'DynaBox' object has no attribute 'colors'"
```

**Comment by mkashwin** [comment]
You need to add this property at the end of your yaml file
dynaconf_merge: true

**Comment by yarinbar** [comment]
Thanks that solved it, although i would have expected it to be the default behaviour

**Comment by mkashwin** [comment]
You could also try passing the param merge_enabled while calling Dynaconf
https://www.dynaconf.com/configuration/


config = Dynaconf(
        envvar_prefix="DYNACONF",
        settings_files=config_files,
        merge_enabled=True
)

**Comment by yarinbar** [comment]
thanks i prefer to use it like that!

**Comment by rochacbruno** [comment]
I will reopen and label it as docs, documentation must be more clear about the default behavior for merging.
