### ISSUE TITLE
Register converters for common django functions

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#865]
What you can do right now is the following:

edit `settings.py`

```python
# on the top import reverse_lazy
from django.urls import reverse_lazy
```

Then after the `import dynaconf`  - before `settings = ...` add

```pythin
dynaconf.utils.parse_conf["@reverse_lazy"] = reverse_lazy
```

Now you should be able to do

On yaml
```yaml
default:
    login_url: "@reverse_lazy account_login"
```

On env vars
```bash
export DJANGO_LOGIN_URL="@reverse_lazy account_login"
```

**NOTE** I have not tested! but if it works we can then add it by default to the context in future versions.

_Originally posted by @rochacbruno in https://github.com/dynaconf/dynaconf/issues/858#issuecomment-1416858641_

**Comment by pedro-psb** [comment]
Closed by #904
