### ISSUE TITLE
[RFC] Specify settings file from environment variable

### ISSUE THREAD

**Issue by MaxG87** [dynaconf/dynaconf#872]
**Is your feature request related to a problem? Please describe.**
I have an application that uses Dynaconf for its configuration. I want to deploy it into K8s using Kustomize. Since I consider the configuration to be part of the deployment specification, I'd like to have the configuration in the Kustomize repository, as a ConfigMap.

As far as I understand I must mount the settings file exactly at the right location for Dynaconf to pick it up. This is a rather unfortunate coupling of the image and the configuration, because it forces me to adapt the deployment files if in the application's image the Python code is moved to a different folder.

**Describe the solution you'd like**

I'd like to mount the settings to somewhere (e.g. /config/) and create an environment variable that tells dynaconf where to look for the configuration file (e.g. `DYNACONF_SETTINGS_FILE=/config/settings.toml`). If present, this environment variable should take precedence over a local config folder.

**Describe alternatives you've considered**
I am currently rewriting the application to do the thing described above manually. I import Dynaconf and assign it to `settings`, manually setting the `settings_file` argument. It is cumbersome. I'd rather not rewrite the application.

**Additional context**
I carefully read the documentation on [environment variables](https://www.dynaconf.com/envvars/) and [settings files](https://www.dynaconf.com/settings_files/). I couldn't find the feature in there.

**Comment by rochacbruno** [comment]
Hi, it is already implemented

https://www.dynaconf.com/configuration/#settings_file-or-settings_files

```bash
# singular
export SETTINGS_FILE_FOR_DYNACONF="/etc/program/settings.toml"

# multiple
export SETTINGS_FILES_FOR_DYNACONF="/etc/program/settings.toml;/tmp/foo.yaml"
```

**Comment by rochacbruno** [comment]
we need to improve the docs adding that note to the `settings files` section

**Comment by pedro-psb** [comment]
Also, this specific question could be added to a FAQ. There would be already two questions with #880 hehe
