### ISSUE TITLE
[bug] `dynaconf validate ` not working with `dynaconf_validators.toml`

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#879]
### Discussed in https://github.com/dynaconf/dynaconf/discussions/868

<div type='discussions-op-text'>

<sup>Originally posted by **Holzhauer** February 14, 2023</sup>

> I attempt to validate the type of a variable in `dynaconf_validators.toml`. However, if I code it as
> 
> `startyear = {is_type_of=int}`
> 
> I get a `dynaconf.vendor.tomllib.TOMLDecodeError: Invalid value` for the character after "=". If I set the type in quotes like
> 
> `startyear = {is_type_of="int"}`
> 
> I get a `TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union`.
> What is the correct syntax here?

</div>

---

I'll describe the bug from the initial discussion but I think there is more room to improvement in the implementation of the `dynaconf validate`

### Describe the bug

When trying to cast a value to `int` using the cli tool `dynaconf validate` and the file `dynaconf_validators.toml`, there program raises a `TypeError`. Also, a wrong use of TOML format using unquoted `int` raises an unhandled `tomllib` specific error.

### To Reproduce

1) Download [gist sample](https://gist.github.com/pedro-psb/d26a78d2d3742b1086d935ba8e9bd109), setup a virtualenv, pip install `dyanconf`  and execute `dynaconf -i config.settings validate`. It should raise a TypeError.

Shortcut:

```bash
# get code
git clone https://gist.github.com/d26a78d2d3742b1086d935ba8e9bd109.git issue-879 && cd issue-879

# review and execute
cat run.sh
chmod +x run.sh
./run.sh
```

2) Using unquoted `int` raises some unhandled `tomllib` errors.

### Expected behavior

1) Validate the settings without any problem
2) Handle error to suggest it should probably be quoted.

### Environment

- OS: Ubuntu 22.04
- Python Version: 3.11.2
- Dynaconf Version: 3.1.12

---
### Additional comments

I've found that the cli command `validate` has some other bugs and could be better tested. Eg, if in this code sample the `environments` setting was false, and there were no `[default]` in the `.toml`, the output would be:

```bash
Invalid rule for parameter 'is_type_of'
Validation success!
```

I'd like to propose to write some more unit test for this command and try to fix these inconsistencies. Should I create another issue for that?

[edit: add gist sample code]

**Comment by rochacbruno** [comment]
The expected way for this to work given the toml parser would be

```toml
startyear = {is_type_of="@int"}
```

I am not sure this is supported, but must be

**Comment by pedro-psb** [comment]
> The expected way for this to work given the toml parser would be
> 
> ```toml
> startyear = {is_type_of="@int"}
> ```
> 
> I am not sure this is supported, but must be

This still throws the same error

**Comment by pedro-psb** [comment]
## Problem analysis

I had a look at the code and `cli.py` doesn't use the custom parser which deals with `"@int"` converters in the `dynaconf_validators.toml` file, it directly parses it with tomllib or toml. [source](https://github.com/dynaconf/dynaconf/blob/46d3ab4e256212305fb3103847d56344dc339b46/dynaconf/cli.py#LL726-L735C10)

After parsing, here is what happens in `cli.py`: ([source](https://github.com/dynaconf/dynaconf/blob/46d3ab4e256212305fb3103847d56344dc339b46/dynaconf/cli.py#LL757-L763C36))

```diff
# this is inside a loop through `dynaconf_validators.toml` in-memory structure where:
# name -> "startyear"
# data -> dict = { 'is_type_of' = '@int' }
try:
-    Validator(name, **data).validate(settings)
+    Validator("startyear", is_type_of="@int").validate(settings) 
except ValidationError as e:
    click.echo(
        click.style(f"Error: {e}", fg="white", bg="red")
    )
    success = False
```

Having a look at  `Validator` usage, it should receive an `int` class (a type class) so, for this to work, a converter would need to be implemented:

```python
# data -> dict = { 'is_type_of' = '@int' }
data = convert_to_type_class(data)
# data -> dict = { 'is_type_of' = int }
Validator(name, **data).validate(settings)
```
## Sample solution

I've actually tested a simple implementation using a convert map, and it indeed works. It is not able to force types, but maybe it shouldn't (for consistence).

Here is the outcomes after implementing the converter:

```bash
# for all cases
# - dynaconf_validators.toml -> startyear = {is_type_of="@int"}

# case 1: toml-is-int
# - settings.toml > startyear = 12
$ dynaconf -i config.settings validate
> Validation success!

# case 2: toml-is-str
# - settings.toml > startyear = "12"
$ dynaconf -i config.settings validate
> Validating 'startyear' with '{'is_type_of': '@int', 'env': 'default'}'
> Error: startyear must is_type_of <class 'int'> but it is 12 in env default
Validation error!

# case 3: toml-is-converter-to-int
# - settings.toml > startyear = "@int 12"
$ dynaconf -i config.settings validate
> Validation success!
```

## Conclusion

First, I thought the types inside `dynaconf_validators.toml` should actually be used as `"int"` (not `"@int"`), so it is clear that it will not try casting types and will strictly validate what is loaded from `settings.toml`. It seems the expected behavior for validating and is easy enough to fix.

But maybe there should be a "@type int" marker. From a design perspective, this really seems more appropriate, as it would avoid introducing unnecessary special case handling by leveraging the existing casting system. In this case, the parsing section of `cli.py:validate` would need to be re-implemented to use the same parsing process as in loading settings, which already can process markers. It would take a little more work, but seems the right way.
