### ISSUE TITLE
[CI] Skip tests if changes are made only to docs/ folder

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#883]
When a PR includes only changes to docs/ folder the whole CI for tests must be skipped, the only workflow required would be the netlify preview build

example https://github.com/dynaconf/dynaconf/pull/882

To solve this we need to explore on how to skip workflows conditionally and use git diff to list all the changed files

**Comment by pedro-psb** [comment]
[This section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) of the docs seems to provide a good solution for that.

According to the blue note there, it may cause some issues with blocking merges, but I'm not sure.
