### ISSUE TITLE
[RFC] change design for Avaliable Options in docs

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#884]
**Is your feature request related to a problem? Please describe.**

I'd like to propose a design change in the [Configuration > Available Options](https://www.dynaconf.com/configuration/#available-options) section of the docs. As issue #872 has shown, even though the information was present, a better design could have helped the user find what he needed faster.

Also, the options are almost all sorted, but `filtering_strategy`, `dotted_lookup` and `apply_default_or_none` are not.

**Describe the solution you'd like**

I've tried some options using markdown features and I've came up with these two.

\#1 header in keyword style
> ![Screenshot from 2023-03-09 19-14-22](https://user-images.githubusercontent.com/7907864/224172408-905d0f1a-4f5b-443e-96e4-53f1dadb5bb9.png)

\#2 header in keyword style with more breath space
> ![Screenshot from 2023-03-09 19-14-13](https://user-images.githubusercontent.com/7907864/224172429-f399968a-cf8b-4669-811d-c1e0def87f15.png)

**Describe alternatives you've considered**

I've tried to put all values in one line, but it may cause awkward line breaks if the line is too long.

**Additional context**

Anyway, I think the items should be sorted correctly

**Comment by pedro-psb** [comment]
I prefer option \#2, with more breath.

**Comment by rochacbruno** [comment]
I like option 2

**Comment by pedro-psb** [comment]
I guess [envvar](https://www.dynaconf.com/configuration/#envvar) definition is actually the `settigns_files` definition:

> This variable changes the location of the settings file that loads the environment variables,
> ex: `export SETTINGS_FILE_FOR_DYNACONF=another/path/settings.toml`

I've run a quick test to prove my hypothesis and I would propose this definition instead:

> Sets an environment variable name to override the default [settings_files](#link).
> ex:
>   ```bash
>   # sets MY_PATHS as the new env var that defines the paths to the settings files.
>   export ENVVAR_FOR_DYNACONF="MY_PATHS"
>   # now this can be used to override what is defined in *settings_files* or SETTINGS_FILES_FOR_DYNACONF
>   export MY_PATHS"="path.to.settings"
>   ```

There sure are more subtleties about how that override goes, but that would give a better overview of its behaviour.

**Comment by pedro-psb** [comment]
In [settings_files](https://www.dynaconf.com/configuration/#settings_file-or-settings_files), what does this means, exactly?

> Starting on v3.0.0 dynaconf will load only files specified on this variables.

It means `envvar` will no longer be available to override it? If that is so, this is not true, because it is still working on v3.1.12

**Comment by rochacbruno** [comment]
@pedro-psb before 3.0 dynaconf had a fixed list of settings file to look if user didn't provide a list of files, on 3.0 it was deprecated so user is now required to pass a list of files either by

- settings_file or settings_files attr
- SETTINGS_FILE_FOR_DYNACONF (or the alias SETTINGS_FILES_FOR_DYNACONF)
- Using the custom prefix set on the envvar like MY_PATHS from your example.

Ideally there would be only one way for doing it, however the library grew in a way we avoided breaking compatibility.

On the docs I think we should have only the recommended ways highlighted and the alternative ways mentioned on the bottom reference or FAQ.

The preferred way to set the settings files is by passing the attr `settings_files=[]` to the  `Dynaconf` constructor, 
This variable can also be overriden by the envvar `SETTINGS_FILES_FOR_DYNACONF` (IIRC it accepts a string separated by ; for multiple paths)

Alternatively it is possible to set a custom variable like `MY_PROGRAM_CONFIG=/etc/program/config.toml` by passing `envvar="MY_PROGRAM` to the isntance. (I know, the name of this variable is not good, should have callaed it file_list_variable="VALUE" but it is like this fir historical reasons.

**Comment by pedro-psb** [comment]
Ok, this resolves my confusion.

In this PR I'll also propose some small changes in the content of `settings_files`and `envvar` to reflect this information.

**Comment by pedro-psb** [comment]
> **On the docs** I think we should have only the recommended ways highlighted and the alternative ways mentioned on the **bottom reference** or FAQ.

Just for clarification:

- **Bottom reference** refers to the [Configuration](https://www.dynaconf.com/configuration/) page, which is kinda like an API reference and is supposed to be exhaustive.
- **On the docs** refer to any other more guide-like page, such as [Settings Files](https://www.dynaconf.com/settings_files/)
