### ISSUE TITLE
[RFC] Docs: re-structure Validation Page hierarchy

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#911]
**Is your feature request related to a problem? Please describe.**
I think the Validation page has some points that could be enhanced for a better reading experience:
- headers are a little hard to navigate
- some introductory examples have too much information (which distracts from explaining the basics)

**Describe the solution you'd like**

I'd suggest the following grouping to address both problems pointed out previously.

```
Overview
Usage
	With Python
		On instantiation
		Lazy validation
	With CLI
Features
	Multiple validators
	Custom messages
	Default and computed values
	Casting / Transform
	Custom conditional expressions
	Inter-related Validation
	Combination Operators
	Selective Validation
Sample examples (longer/full examples moved here)
Reference (actually #validator-parameters)
```

Note that there are some sub-headings suppressed here. It is part of the proposal to leave sub-headings in the text but suppress them in the *table of content menu*, which can be achieved by using `<h3>` tags instead of markdown syntax `###`

There are also some renaming of titles, which I understand that may be very personal and subjective.

**Describe alternatives you've considered**
I haven't considered alternatives.

**Additional context**
None.

**Comment by sebastian-correa** [comment]
Forgot to add, but I'm working on this. More context on #968.
