### ISSUE TITLE
[bug] Integer like array is not cast to string even if said so.

### ISSUE THREAD

**Issue by FeryET** [dynaconf/dynaconf#922]
**Describe the bug**
I am trying to have a number only string as a value in the dynaconf setting object, but the parser only treats it as a number.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

# /path/
# ...../folder/...
# please provide your folder structure here

```
</details>

2. Having the following config files:

<details>

```TOML
# settings.toml
[default]
password = 123456
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/config.py**
```python
from dynaconf import Dynaconf, Validator

settings = Dynaconf(
    environments=True,
    settings_files=["settings.toml", ".secrets.toml"],
    root_path=os.path.dirname(os.path.abspath(__file__)),
    validators=[
         Validator("PASSWORD", must_exist=True, cast=str)
    ],
)
```

**/path/src/app.py**
```python
from config import settings
assert settings.password == "123456" # This throws an error and can only read the password as an integer.
```

**Comment by pedro-psb** [comment]
This didn't work in  `v3.1.11` but was fixed by #873. 
In `v3.1.12` it works as expected

**Comment by pedro-psb** [comment]
@FeryET Can you confirm upgrading solves the issue?

**Comment by FeryET** [comment]
@pedro-psb Sorry for the late reply, I could test it just now. Seems to be working in the new version.
