### ISSUE TITLE
dynaconf_merge=False not working with hooks [bug]

### ISSUE THREAD

**Issue by Holzhauer** [dynaconf/dynaconf#926]
**Describe the bug**
The documentation (https://www.dynaconf.com/advanced/#hooks) states: "To disable the merging of the data, you can set the dynaconf_merge to False." However, this is not true. Even setting dynaconf_merge to False merges the object returned by post() into existing settings.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash
files/testing/settings.toml
files/testing/dynaconf_hooks.py
src/main.py
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**/path/.env**
```bash
Your .env content here
```

and

**/path/settings.toml**
```toml
[default]
DEBUG = true
Name="Test"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**main.py**
```python
from dynaconf import LazySettings

settings = LazySettings(
    environments=True,
    ENV_FOR_DYNACONF="default",
    ENVVAR_PREFIX_FOR_DYNACONF="none",
    load_dotenv=True,
    settings_files="../files/testing/settings.toml",
)

print(settings.as_dict())
```

**dynaconf_hooks.py**
```python
def post(settings):
    data = {"dynaconf_merge": True}
    if settings.DEBUG:
        data["DATABASE_URL"] = "sqlite://"
    return data
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# other commands and details?
# virtualenv activation?

$ python main.py
```

</details>

**Expected behavior**
{'LOAD_DOTENV': True, 'DATABASE_URL': 'sqlite://'}

**Actual behavior**
{'LOAD_DOTENV': True, 'DEBUG': True, 'NAME': 'Test', 'DATABASE_URL': 'sqlite://'}

**Environment (please complete the following information):**
 - OS: Windows 11]
 - Dynaconf Version 3.1.12

**Comment by pedro-psb** [comment]
This is a more general issue. The current implementation of local `dynaconf_merge`s does not support the False flag as it should.
Being tracked in #835

**Comment by pedro-psb** [comment]
In this specific example, it is expected that the values will merge even if merge is set to `False', because top level structure always merges (it isn't affected by the merge flags and marks).

I've added a workaround in #957 functional test for this, which consists in:
- explicit deleting other keys OR
- nesting values in wrapper namespace (which now works with `dynaconf_merge=False`).

We should present this more explicitly in the docs.
