### ISSUE TITLE
[RFC] Support for username and password with vault

### ISSUE THREAD

**Issue by hansharhoff** [dynaconf/dynaconf#927]
**Is your feature request related to a problem? Please describe.**
Dynaconf currently does not support connecting to Hashicorp Vault using username and password.

**Describe the solution you'd like**
I suggest adding support for username and password.

**Describe alternatives you've considered**

**Additional context**
hvac already supports username and password and I've tested an implementation locally and could provide pull request if you like the approach.

**Comment by pedro-psb** [comment]
Thanks for the contribution @hansharhoff !
