### ISSUE TITLE
Documentation for cast wrong?

### ISSUE THREAD

**Issue by Mardoxx** [dynaconf/dynaconf#930]
https://www.dynaconf.com/#reading-settings-variables
>settings("number", cast=int)                  # customizable forcing of casting

If we follow the code through we get to parse_config.converters, which is a dict[str, ...]

https://github.com/dynaconf/dynaconf/blob/86c81cf6823004dbbcd53381caa48b3fc5bd482d/dynaconf/utils/parse_conf.py#L231-L267

Is the value of cast meant to be a string always with these magic strings, or did you forget to put the types in for basic types! 😄

**Comment by rochacbruno** [comment]
Hi @Mardoxx the value for `cast` must be `cast="@int"` for hystorical reasons, however I feel like we must add and Enum now that Python has it and provide, Dynaconf.INT etc...

**Comment by pedro-psb** [comment]
> Hi @Mardoxx the value for `cast` must be `cast="@int"` for hystorical reasons, however I feel like we must add and Enum now that Python has it and provide, Dynaconf.INT etc...

Agreed. May put it should live in it's own namespace/obj for a more strict auto-completion: `Cast.INT` (imported) or `Dynaconf.Cast.INT`.
