### ISSUE TITLE
Validator with different environments has weird behaviour

### ISSUE THREAD

**Issue by sebastian-correa** [dynaconf/dynaconf#968]
**Describe the bug**
When running `MY_PROGRAM_STAGE=development python test.py`, I get `dynaconf.validator.ValidationError: TEST_1 is required in env production` when the environment has been set to `development`.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash
.
├── test.py
└── test.yaml

1 directory, 2 files
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**test.yaml**
```yaml
production:

development:
  TEST_2: "bar"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**test.py**
```python
from pathlib import Path

from dynaconf import Dynaconf, Validator

settings = Dynaconf(
    settings_files=[Path.cwd() / "test.yaml"],
    environments=True,
    env_switcher="MY_PROGRAM_STAGE",
    envvar_prefix="MY_PROGRAM",
    merge_enabled=True,
    validators=[
        Validator("TEST_1", env="production", must_exist=True),
        Validator("TEST_2", env="development", must_exist=True),
    ],
)

print(settings.items())
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>
* Python 3.10.8 (main, May 18 2023, 20:50:03) [Clang 14.0.3 (clang-1403.0.22.14.1)]
* Poetry (version 1.4.2)
* `dynaconf == 3.1.12`
</details>

**Expected behavior**
Running `MY_PROGRAM_STAGE=development python test.py` should not fail because we're not running in `production`, so it shouldn't matter that there's no value for `TEST_1`.

**Environment (please complete the following information):**
* OS: MacOS 13.3.1 (22E261), M1 Pro.
* Python 3.10.8 (main, May 18 2023, 20:50:03) [Clang 14.0.3 (clang-1403.0.22.14.1)]
* Poetry (version 1.4.2)
* `dynaconf == 3.1.12`
*  Frameworks in use: None.

**Comment by sebastian-correa** [comment]
Hey @pedro-psb. You're right! It's a documented behavior. I've been through that part of the docs and never connected the dots; maybe also giving it more prominence in the docs with a subheading would help?

I do like your enhancement proposal. I guess the only alternative I can think of is having this be a kwarg to make it easier to find, but the `validate_options` idea seems more flexible.

_I'll test your proposal in our real codebase as soon as I can and report back 😄._

---
While at it, I think that the `current_env` instance variable could use more prominent documentation (see [this](https://www.google.com/search?q=current_env+site%3Adynaconf.com) search, where none of the results explain what it does or are easily discoverable).

Maybe using that section to link to the section you mentioned would also help avoid this issue I had, but I'm inexperienced when it comes to maintaining open source libraries with a user base as big as Dynaconf's so it might as well be more confusing.

**Comment by pedro-psb** [comment]
I agree documentation can be improved. Minor documentation-only changes could be:
- Change `Validate only current env` title to a proper heading which will show in the `Validation` TOC
- Add this case to the FAQ, which is a workaround for making it easy to find some stuff
- I didn't understand exactly where the link you suggested would be, but this should probably help too.

Some months ago, I've written a small re-write proposal of the Validation page (#911) with the purpose of tackling this kind of information-finding issues. I haven't carried it forward for lack of time/priority.

### Extra considerations

I've had a better look at the section and codebase and I've found more:
- you can actually pass `validate_only_current_env=True` to `Dynaconf` instantiation. [code link](https://github.com/dynaconf/dynaconf/blob/9ca687a4e6df9d67cf060a1fe092a782a256ec24/dynaconf/base.py#L239), which looks undocumented.

```python
settings = Dynaconf(
    ...
    validators=[
        Validator("TEST_1", env="production", must_exist=True),
        Validator("TEST_2", env="development", must_exist=True),
    ],
    validate_only_current_env=True,
)
```
- there is a partial implementation to pass `validate` options inside `ValidationList`, which I think is better than the direct `Dynaconf` param above (it is more scoped/easier to find). ([code link](https://github.com/dynaconf/dynaconf/blob/9ca687a4e6df9d67cf060a1fe092a782a256ec24/dynaconf/validator.py#L452)). It looks like the options are popped from the ValidatorList but never actually used (haven't tested).

```python
settings = Dynaconf(
    ...
    validators=[
        Validator("TEST_1", env="production", must_exist=True),
        Validator("TEST_2", env="development", must_exist=True),
        validate_exclude=(...), # 'saved' but not used?
        validate_only_current_env=True, # not even partially implemented
    ],
)
```

With these findings, I think it would be better to choose one of these two ways to document/fix/enhance the issue, instead of my previous idea.

**Comment by sebastian-correa** [comment]
> I didn't understand exactly where the link you suggested would be, but this should probably help too.

Currently there's no clear documentation I can (easily) find on the `current_env` instance variable. I've been using it for a while, but I discovered it from a `dir(settings)` call. If we added a small tid-bit somewhere in the docs about this variable, we could say something like "Keep in mind that, by default, validation happens for all envs".

If we document the `validate_only_current_env` kwarg, this is not necessary as it'll be evident what the default is and how to change it. Some clearer documentation on `current_env` would be welcomed anyways. 

> With these findings, I think it would be better to choose one of these two ways to document/fix/enhance the issue, instead of my previous idea.

I agree. Thanks for the research you've put into this; it now looks like a mere documentation problem. I haven't gotten around to testing this yet, but I'll try passing `validate_current_env` to `Dynaconf` to see what happens.

Your second example doesn't work for me, though. Fails with a `SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?` (which makes sense to me). I think we'd have to import the `ValidatorList` and it becomes a bit cumbersome to use if this is the only supported way to only validate the current env.

I also skimmed through the `ValidatorLIst`, and it looks like it needs a `settings` instance passed to it, so I'm not sure it'd be possible to do on `Dynaconf` instantiation. Can you shed some light?

**Comment by rochacbruno** [comment]
I agree that `validate_current_env` must default to `True` but we can do it only on the next major version, `4.0.0`

**Comment by sebastian-correa** [comment]
Hey @pedro-psb, I just got around to testing this. Your first suggestion [here](https://github.com/dynaconf/dynaconf/issues/968#issuecomment-1680796841) worked like a charm:
```python
settings = Dynaconf(
    ...
    validators=[
        Validator("TEST_1", env="production", must_exist=True),
        Validator("TEST_2", env="development", must_exist=True),
    ],
    validate_only_current_env=True,
)
```

@rochacbruno, thanks for adding this to the 4.0.0 milestone. I do agree this should be the default, and I also agree this is a major version thing. I do think the enhancements to the documentation mentioned by @pedro-psb and myself could still be implemented in 3.X.Y. Don't you agree?

**Comment by rochacbruno** [comment]
I agree @sebastian-correa let's document the solution you tested

**Comment by sebastian-correa** [comment]
I don't have much experience with some of the features in the Validation section, and I also don't want to butcher it, but I can draft a PR to solve #911 and also add some small sections in the Configuration page.

This'd be a draft to do the tedious work, but I'd be fine if you took over and edited it further; or if the PR got closed altogether in favor of another proposal.

Let me know if it's fine, @pedro-psb and @rochacbruno.

**Comment by pedro-psb** [comment]
@sebastian-correa This sound great! I'll happily review and help out with that.

The configuration page should include `validate_only_current_env` and the other available options for Validate:`validate_only` and `validate_exclude`.

**Comment by sebastian-correa** [comment]
I started some work on my fork, but didn't push it. I'll take a look at it this weekend!

**Comment by sebastian-correa** [comment]
Submitted #989. Let's discuss there :). Please do ask for any changes (or rollbacks) you feel are necessary, I want this to have the best possible outcome for the project :).
