### ISSUE TITLE
YAML: Integer Keys Stored as Strings 

### ISSUE THREAD

**Issue by sanssecours** [dynaconf/dynaconf#969]
**Describe the bug**

Integer keys in A YAML configuration file are returned as strings, not as integers

**To Reproduce**

1. Having the following folder structure

   <details>

   ```
   .
   ├── config.yaml
   └── test.py

   2 directories, 1 file

   ```

   </details>

2. Having the following config files:

   <details>
   <summary> Config files </summary>

   **config.yaml**

   ```yaml
   tools:
     1: something
     2: moar
   ```

   </details>

3. Having the following app code:

   <details>
   <summary> Code </summary>

   **test.py**

   ```python
   from pathlib import Path

   from dynaconf import Dynaconf

   settings = Dynaconf(settings_files=[Path(__file__).parent / "config.yaml"])

   print(settings.tools)
   ```

   </details>

4. Executing under the following environment

   <details>
   <summary> Execution </summary>

   ```bash
   python test.py
   ```

   </details>

**Expected behavior**

The code should print the following output (and does so using Dynaconf `3.1.12`):

```
{1: 'something', 2: 'moar'}
```

**Actual behavior**

The code prints the following output:

```
{'1': 'something', '2': 'moar'}
```

**Environment:**

- OS: macOS `13.5`
- Dynaconf Version `main` (or `3.2.0`)

**Additional context**

I do not think that this is a problem of [`ruamel.yaml`](https://pypi.org/project/ruamel.yaml/) since the following code:

```py
from pathlib import Path

from ruamel.yaml import YAML

YAML = YAML()
print(YAML.load(Path("config.yaml"))["tools"])
```

prints the expected output:

```
{1: 'something', 2: 'moar'}
```

**Comment by rochacbruno** [comment]
I am not considering this a bug because this is expected and a known caveat of our key system, I am open to change it adding the functionality.

**Comment by sanssecours** [comment]
Thank you for the quick reply.

> I am not considering this a bug because this is expected and a known caveat of our key system, I am open to change it adding the functionality.

That makes sense. Thank you for considering to change the behavior. Just for reference: My use case was code that looks something like this:

```python
if tool_number in settings.tools:
    # do something useful
```

**Comment by rochacbruno** [comment]
So, this is actually a bug introduced on 3.2.0 version, Box keys are being converted to string

## 3.1.12
![2023-08-03_16-19](https://github.com/dynaconf/dynaconf/assets/458654/1ca07173-ddda-4c94-99ee-57f451455fa8)

## 3.2.0
![2023-08-03_16-22](https://github.com/dynaconf/dynaconf/assets/458654/7d22372b-2315-43ba-a99a-7f1b5980d98d)

**Comment by rochacbruno** [comment]
So there a re 2 problems to be resolved

1. First level keys, by design, must be strings, we need to accept other types and document that those keys are impossible to access via dotnotation, this also impacts the ability to use `__` for merging nested data.
2. Inside a data structure like DynaBox, the original type must be kept

**Comment by pedro-psb** [comment]
This was introduced by me (#920) because I was optioned to not allow arbitrary key-types and ended up overlooking the breaking change it would cause.

I've also noticed that I didn't add tests for this PR (which solves #919), so it would be good to include 919 problem in this fix.
