### ISSUE TITLE
[bug] Unable to load configuration files using the `*` wildcard

### ISSUE THREAD

**Issue by kidrahahjo** [dynaconf/dynaconf#982]
**Describe the bug**
Unable to load yaml configuration file using the `*` wildcard in `setting_files` argument

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash
# project.py
# .config/data_sources.yaml
# settings.toml
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**.config/data_sources.yaml**
```yaml
DEFAULT:
  DATA_SOURCES:
    NAME: 1
```

and

**settings.toml**
```toml
[default]
LOG_LEVEL="INFO"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**project.py**
```python
from dynaconf import Dynaconf

settings = Dynaconf(
  environments=True,
  lowercase_read=False,
  load_dotenv=True,
  settings_files=["settings.toml", ".config/*.yaml"]
)

print(settings.LOG_LEVEL)
print(settings.DATA_SOURCES)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python project.py
```

</details>

**Expected behavior**
When running the script it should first print "INFO" (value for LOG_LEVEL) and then print {"name": 1} (value for DATA_SOURCES as specified in `.config/data_sources.yaml`)
This works as expected when I specify `settings_files=["settings.toml", ".config/data_sources.yaml"]` (without the * wildcard).

**Environment (please complete the following information):**
 - OS: CentOS Linux Release 7.9.2009 (Core)
 - Dynaconf Version: 3.2.0
 - Python version: 3.10.8

**Comment by rochacbruno** [comment]
fix in #987
