### ISSUE TITLE
[bug] KeyError: '_bypass_evaluation' in Dynaconf 3.2.1

### ISSUE THREAD

**Issue by JacobCallahan** [dynaconf/dynaconf#984]
**Describe the bug**
The change introduced in PR #966 also introduced a KeyError in our tests.

**To Reproduce**
Not currently clear without digging further into the cause, but this was triggered in our tests using multi-threading. You can see the failures in the github action link here: https://github.com/SatelliteQE/broker/actions/runs/5928071069/job/16074442428?pr=227

**Expected behavior**
This KeyError should not be triggered. Instead, there should likely be a check that the key exists before attempting to pop or give a default pop value of None.
```python
self._store._box_config.pop("_bypass_evaluation", None)
```

**Comment by JacobCallahan** [comment]
@pedro-psb this should be an easy fix :)

**Comment by rochacbruno** [comment]
@JacobCallahan https://github.com/dynaconf/dynaconf/pull/985 this is a hotfix

However looks like we have a bigger problem with the multi-threading to investigate

**Comment by JacobCallahan** [comment]
Thanks for the quick fix @rochacbruno!
