### ISSUE TITLE
[bug] Validation time increased more than 10 times in dynaconf 3.2.0

### ISSUE THREAD

**Issue by ogajduse** [dynaconf/dynaconf#986]
**Describe the bug**
After an update from dynaconf 3.1.12 to 3.2.0, we noticed a significant validation time increase.

I have added a time measuring around our settings.validators.validate() in https://github.com/SatelliteQE/robottelo.
With dynaconf 3.2.0:
`2023-08-15 16:27:54 - robottelo - INFO - Dynaconf validation took 14.501641750335693 seconds`
with dynaconf 3.1.12:
`2023-08-15 16:30:40 - robottelo - INFO - Dynaconf validation took 1.3247039318084717 seconds`

**To Reproduce**
* `git clone https://github.com/SatelliteQE/robottelo`
* `pip install .`
* `for conffile in conf/*.yaml.template; do mv -- "$conffile" "${conffile%.yaml.template}.yaml"; done`
* `time python -c 'from robottelo.config import settings'`

**Expected behavior**
validation time to be the same as in the older dynaconf version or faster :smile: 

**Environment (please complete the following information):**
 - OS: Fedora 37
 - Dynaconf Version 3.2.0
 - Python 3.11.4

**Comment by rochacbruno** [comment]
This issue will probably be addressed by #981 

The time increased because of this change https://github.com/dynaconf/dynaconf/pull/892/files#diff-32c3b833b4d892e0c8c968669eb1875096b9e7ef19024dff76f32c2771669615L285 which makes all validators to call `.set` for every key.

With #981 validation will not set values anymore then will be faster.

**Comment by pedro-psb** [comment]
> Did you try profiling dynaconf before?

@ogajduse Not really, I would dig into that now.

> I could profile it and see what makes the validation run that long.

I think that's the way to go. It should be easy to spot where the hotspot is, but you could also share the pstats file here so we can have a look (assuming you're using cProfile).

**Comment by ogajduse** [comment]
I do not observe this issue anymore. I am unable to pinpoint what was causing it, unfortunately.
I am closing this issue, feel free to reopen it.

**Comment by ogajduse** [comment]
Reopening since I bumped into it again.
@pedro-psb I have used the Dockerfile you provided and did a test run.
The only thing that I changed in the Dockerfile was the CMD from which I removed the config manipulation line. I built an image and ran it.

```
$ podman run -t -v /home/ogajduse/repos/robottelo/conf:/root/robottelo/conf:Z -v /home/ogajduse/repos/robottelo/.env:/root/robottelo/.env:Z robottelo-test
installing dynaconf as editable package...

3.2.3
2023-11-29 13:50:58 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
    vlan_networking.subnet is required in env main
2023-11-29 13:50:58 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
    vlan_networking.subnet is required in env main
21.70user 0.09system 0:22.78elapsed 95%CPU (0avgtext+0avgdata 66728maxresident)k
0inputs+24outputs (0major+12364minor)pagefaults 0swaps
/root/robottelo

3.1.12
2023-11-29 13:51:03 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
    vlan_networking.subnet is required in env main
2023-11-29 13:51:03 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
    vlan_networking.subnet is required in env main
3.30user 0.08system 0:04.22elapsed 79%CPU (0avgtext+0avgdata 66764maxresident)k
32inputs+32outputs (0major+12282minor)pagefaults 0swaps
```

I have injected my configuration into the container as well as the .env file with a HashiCorp Vault token.

I have figured out that if I remove validators for `repos` settings, I get results in around 3-4 seconds.
https://github.com/SatelliteQE/robottelo/blob/bcc4d305535918b53c6892b4733ad9c44fb26fda/robottelo/config/validators.py#L249-L267

I will investigate more and post the results here.

**Comment by ogajduse** [comment]
I must have had something weird in my local config. Unfortunately, I did not back it up, so I can not elaborate on it more. Closing the issue. Thank you for your attention. :slightly_smiling_face:
