### ISSUE TITLE
[bug] two validators with defaults break string casting of lists in .env file

### ISSUE THREAD

**Issue by aqc-carlodri** [dynaconf/dynaconf#992]
**Describe the bug**
Having two validators with defaults break string casting of lists in `.env` file

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

    .env
    .gitignore
    config.py

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**.env**
```bash
DYNACONF_GROUP__TEST_LIST = ["'1'", "'2S'"]

DYNACONF_GROUP__ANOTHER = 45
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**config.py**
```python
from dynaconf import Dynaconf, Validator

settings = Dynaconf(
    load_dotenv=True,
    environments=True,
)


settings.validators.register(
    Validator("group.something_new", default=2),
    Validator("group.another_new", default=3),
)

settings.validators.validate()
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
dynaconf -i config.settings list
```

</details>

**Expected behavior**
Expected output of the above command:
```bash
Working in development environment
LOAD_DOTENV<bool> True
GROUP<dict> {'ANOTHER': 45, 'TEST_LIST': ['1', '2S'], 'another_new': 3, 'something_new': 2}
```
Notice the first item of `TEST_LIST`.

**Actual behavior**
Actual output of the above command:
```bash
Working in development environment
LOAD_DOTENV<bool> True
GROUP<dict> {'ANOTHER': 45, 'TEST_LIST': [1, '2S'], 'another_new': 3, 'something_new': 2}
```
Notice the first item of `TEST_LIST`.

**Environment (please complete the following information):**
 - OS: Win10x64
 - Dynaconf Version 3.2.2

**Additional context**
If you comment out one of the two validators, the problem disappears.

Might be related to #988, as mentioned [on gitter](https://matrix.to/#/!iFwTDdeHkvVVXFSpBo:gitter.im/$eaDw23rBqsKSK--cGhrVOhe53y2Io0AnLqoWyOGc0dM?via=matrix.org&via=gitter.im&via=riot.firechicken.net) by @rochacbruno.

**Comment by rochacbruno** [comment]
Validators will stop having defaults on 4.0.0 the issue #1143 describes it
