### ISSUE TITLE
Add Python API documentation / Module reference to the documentation/website

### ISSUE THREAD

**Issue by ecerulm** [dynaconf/dynaconf#997]
**Is your feature request related to a problem? Please describe.**
As explained in #996

dynaconf 2.2.3 has a [Module reference](https://dynaconf.readthedocs.io/en/docs_223/reference/dynaconf.html#) where I can read see all the methods of dynaconf.LazySettings together with a description.

I don't see anything similar in https://dynaconf.com/ , @rochacbruno, confirmed that 
> Hi, since we migrated to mkdocs there is **no API reference documented**, there is a mkdocs plugin that can generate that we just need to setup it.

**Describe the solution you'd like**
@rochacbruno  and @pedro-psb  mentioned that there is a mkdocs plugin called [mkdocstring](https://mkdocstrings.github.io/)
that can be used to generate that kind of api documentation . 

So I guess this mkdocs plugin should be configured/setup/included in the pipeline that generates the website

**Comment by pedro-psb** [comment]
Other good candidates for a reference sections are:
- dynaconf module API (`Validator`, `inspect_settings`, `get_history`, and others explicitly exposed utilities)
- The actual [CLI](https://www.dynaconf.com/cli/) page, which contains mostly the CLI API description. There are some usage examples, but mkdocstrings allows interleaving manual entries with generated entries via some custom markup.
- The actual [Configuration](https://www.dynaconf.com/configuration/) page (but it would require some code changes, so the plugin can parse descriptions and types. Could be tricky).

**Comment by mitches-got-glitches** [comment]
Hello, I'd be interested in picking this one up as a first issue.

I've been thinking about the approach and I have setup a [little demo repo](https://github.com/mitches-got-glitches/mkdocstrings_autoref_demo/tree/main) where I have created a dummy API and have then followed the [automatic code reference pages recipe](https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages) in the `mkdocstrings` docs. You can check out the results in the pages site linked in the README file.

I'm sure there might be some discussion to be had on what's included automatically, whether you might want to exclude things to avoid clutter. I'm guessing some amendments to [this script](https://github.com/mitches-got-glitches/mkdocstrings_autoref_demo/blob/main/scripts/gen_ref_pages.py) would be needed for that but it would require a little experiment once I have an idea what you want. 

What is displayed and what isn't can be tightly controlled by following [the Usage section](https://mkdocstrings.github.io/usage/#autodoc-syntax) of `mkdocstrings` docs although this won't be automated so will create a little more burden on development and potential for gaps. It could however be used to try and model the look and feel that is wanted from the auto-generated API.

Just a couple of other clarifying points:
- What name would you want to give the top level of the Nav? "API Reference" or "API"?
- Would you want it at the bottom of the existing Nav headers?

Look forward to hearing your thoughts.
